/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SDKCore } from "../core.js";
import {
  encodeFormQuery as encodeFormQuery$,
  encodeSimple as encodeSimple$,
} from "../lib/encodings.js";
import * as m$ from "../lib/matchers.js";
import * as schemas$ from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { SDKError } from "../models/errors/sdkerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { Result } from "../types/fp.js";

/**
 * Load recent events for a particular workspace
 */
export async function eventsGetWorkspaceEventsByTarget(
  client$: SDKCore,
  targetID: string,
  workspaceID?: string | undefined,
  afterCreatedAt?: Date | undefined,
  options?: RequestOptions,
): Promise<
  Result<
    operations.GetWorkspaceEventsByTargetResponse,
    | errors.ErrorT
    | SDKError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  const input$: operations.GetWorkspaceEventsByTargetRequest = {
    workspaceID: workspaceID,
    targetID: targetID,
    afterCreatedAt: afterCreatedAt,
  };

  const parsed$ = schemas$.safeParse(
    input$,
    (value$) =>
      operations.GetWorkspaceEventsByTargetRequest$outboundSchema.parse(value$),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return parsed$;
  }
  const payload$ = parsed$.value;
  const body$ = null;

  const pathParams$ = {
    targetID: encodeSimple$("targetID", payload$.targetID, {
      explode: false,
      charEncoding: "percent",
    }),
    workspaceID: encodeSimple$(
      "workspaceID",
      payload$.workspaceID ?? client$.options$.workspaceID,
      { explode: false, charEncoding: "percent" },
    ),
  };

  const path$ = pathToFunc(
    "/v1/workspace/{workspaceID}/events/targets/{targetID}/events",
  )(pathParams$);

  const query$ = encodeFormQuery$({
    "after_created_at": payload$.after_created_at,
  });

  const headers$ = new Headers({
    Accept: "application/json",
  });

  const security$ = await extractSecurity(client$.options$.security);
  const context = {
    operationID: "getWorkspaceEventsByTarget",
    oAuth2Scopes: [],
    securitySource: client$.options$.security,
  };
  const securitySettings$ = resolveGlobalSecurity(security$);

  const requestRes = client$.createRequest$(context, {
    security: securitySettings$,
    method: "GET",
    path: path$,
    headers: headers$,
    query: query$,
    body: body$,
    timeoutMs: options?.timeoutMs || client$.options$.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return requestRes;
  }
  const request$ = requestRes.value;

  const doResult = await client$.do$(request$, {
    context,
    errorCodes: ["4XX", "5XX"],
    retryConfig: options?.retries
      || client$.options$.retryConfig,
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  });
  if (!doResult.ok) {
    return doResult;
  }
  const response = doResult.value;

  const responseFields$ = {
    HttpMeta: { Response: response, Request: request$ },
  };

  const [result$] = await m$.match<
    operations.GetWorkspaceEventsByTargetResponse,
    | errors.ErrorT
    | SDKError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    m$.json(200, operations.GetWorkspaceEventsByTargetResponse$inboundSchema, {
      key: "CliEventBatch",
    }),
    m$.fail("4XX"),
    m$.jsonErr("5XX", errors.ErrorT$inboundSchema),
  )(response, request$, { extraFields: responseFields$ });
  if (!result$.ok) {
    return result$;
  }

  return result$;
}
