/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDKHooks } from "../hooks/hooks.js";
import { SDK_METADATA, SDKOptions, serverURLFromOptions } from "../lib/config.js";
import { encodeJSON as encodeJSON$, encodeSimple as encodeSimple$ } from "../lib/encodings.js";
import { HTTPClient } from "../lib/http.js";
import * as schemas$ from "../lib/schemas.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";

export enum GeneratePostmanCollectionForApiEndpointAcceptEnum {
    applicationJson = "application/json",
    applicationOctetStream = "application/octet-stream",
}

export class ApiEndpoints extends ClientSDK {
    private readonly options$: SDKOptions & { hooks?: SDKHooks };

    constructor(options: SDKOptions = {}) {
        const opt = options as unknown;
        let hooks: SDKHooks;
        if (
            typeof opt === "object" &&
            opt != null &&
            "hooks" in opt &&
            opt.hooks instanceof SDKHooks
        ) {
            hooks = opt.hooks;
        } else {
            hooks = new SDKHooks();
        }

        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
            hooks,
        });

        this.options$ = { ...options, hooks };
        void this.options$;
    }

    /**
     * Get all Api endpoints for a particular apiID.
     */
    async getAllApiEndpoints(
        apiID: string,
        options?: RequestOptions
    ): Promise<operations.GetAllApiEndpointsResponse> {
        const input$: operations.GetAllApiEndpointsRequest = {
            apiID: apiID,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.GetAllApiEndpointsRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            apiID: encodeSimple$("apiID", payload$.apiID, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent("/v1/apis/{apiID}/api_endpoints")(pathParams$);

        const query$ = "";

        const security$ =
            typeof this.options$.security === "function"
                ? await this.options$.security()
                : this.options$.security;

        const context = {
            operationID: "getAllApiEndpoints",
            oAuth2Scopes: [],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = { context, errorCodes: ["4XX", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const responseFields$ = {
            HttpMeta: { Response: response, Request: request$ },
        };

        const [result$] = await this.matcher<operations.GetAllApiEndpointsResponse>()
            .json(200, operations.GetAllApiEndpointsResponse$, { key: "ApiEndpoints" })
            .fail(["4XX", "5XX"])
            .json("default", operations.GetAllApiEndpointsResponse$, { key: "Error" })
            .match(response, request$, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Get all ApiEndpoints for a particular apiID and versionID.
     */
    async getAllForVersionApiEndpoints(
        apiID: string,
        versionID: string,
        options?: RequestOptions
    ): Promise<operations.GetAllForVersionApiEndpointsResponse> {
        const input$: operations.GetAllForVersionApiEndpointsRequest = {
            apiID: apiID,
            versionID: versionID,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input$,
            (value$) =>
                operations.GetAllForVersionApiEndpointsRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            apiID: encodeSimple$("apiID", payload$.apiID, {
                explode: false,
                charEncoding: "percent",
            }),
            versionID: encodeSimple$("versionID", payload$.versionID, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent(
            "/v1/apis/{apiID}/version/{versionID}/api_endpoints"
        )(pathParams$);

        const query$ = "";

        const security$ =
            typeof this.options$.security === "function"
                ? await this.options$.security()
                : this.options$.security;

        const context = {
            operationID: "getAllForVersionApiEndpoints",
            oAuth2Scopes: [],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = { context, errorCodes: ["4XX", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const responseFields$ = {
            HttpMeta: { Response: response, Request: request$ },
        };

        const [result$] = await this.matcher<operations.GetAllForVersionApiEndpointsResponse>()
            .json(200, operations.GetAllForVersionApiEndpointsResponse$, { key: "APIEndpoints" })
            .fail(["4XX", "5XX"])
            .json("default", operations.GetAllForVersionApiEndpointsResponse$, { key: "Error" })
            .match(response, request$, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Find an ApiEndpoint via its displayName.
     *
     * @remarks
     * Find an ApiEndpoint via its displayName (set by operationId from a registered OpenAPI schema).
     * This is useful for finding the ID of an ApiEndpoint to use in the /v1/apis/{apiID}/version/{versionID}/api_endpoints/{apiEndpointID} endpoints.
     */
    async findApiEndpoint(
        apiID: string,
        versionID: string,
        displayName: string,
        options?: RequestOptions
    ): Promise<operations.FindApiEndpointResponse> {
        const input$: operations.FindApiEndpointRequest = {
            apiID: apiID,
            versionID: versionID,
            displayName: displayName,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.FindApiEndpointRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            apiID: encodeSimple$("apiID", payload$.apiID, {
                explode: false,
                charEncoding: "percent",
            }),
            displayName: encodeSimple$("displayName", payload$.displayName, {
                explode: false,
                charEncoding: "percent",
            }),
            versionID: encodeSimple$("versionID", payload$.versionID, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent(
            "/v1/apis/{apiID}/version/{versionID}/api_endpoints/find/{displayName}"
        )(pathParams$);

        const query$ = "";

        const security$ =
            typeof this.options$.security === "function"
                ? await this.options$.security()
                : this.options$.security;

        const context = {
            operationID: "findApiEndpoint",
            oAuth2Scopes: [],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = { context, errorCodes: ["4XX", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const responseFields$ = {
            HttpMeta: { Response: response, Request: request$ },
        };

        const [result$] = await this.matcher<operations.FindApiEndpointResponse>()
            .json(200, operations.FindApiEndpointResponse$, { key: "ApiEndpoint" })
            .fail(["4XX", "5XX"])
            .json("default", operations.FindApiEndpointResponse$, { key: "Error" })
            .match(response, request$, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Delete an ApiEndpoint.
     *
     * @remarks
     * Delete an ApiEndpoint. This will also delete all associated Request Logs (if using a Postgres datastore).
     */
    async deleteApiEndpoint(
        apiID: string,
        versionID: string,
        apiEndpointID: string,
        options?: RequestOptions
    ): Promise<operations.DeleteApiEndpointResponse> {
        const input$: operations.DeleteApiEndpointRequest = {
            apiID: apiID,
            versionID: versionID,
            apiEndpointID: apiEndpointID,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.DeleteApiEndpointRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            apiEndpointID: encodeSimple$("apiEndpointID", payload$.apiEndpointID, {
                explode: false,
                charEncoding: "percent",
            }),
            apiID: encodeSimple$("apiID", payload$.apiID, {
                explode: false,
                charEncoding: "percent",
            }),
            versionID: encodeSimple$("versionID", payload$.versionID, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent(
            "/v1/apis/{apiID}/version/{versionID}/api_endpoints/{apiEndpointID}"
        )(pathParams$);

        const query$ = "";

        const security$ =
            typeof this.options$.security === "function"
                ? await this.options$.security()
                : this.options$.security;

        const context = {
            operationID: "deleteApiEndpoint",
            oAuth2Scopes: [],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = { context, errorCodes: ["4XX", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "DELETE",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const responseFields$ = {
            HttpMeta: { Response: response, Request: request$ },
        };

        const [result$] = await this.matcher<operations.DeleteApiEndpointResponse>()
            .void(200, operations.DeleteApiEndpointResponse$)
            .fail(["4XX", "5XX"])
            .json("default", operations.DeleteApiEndpointResponse$, { key: "Error" })
            .match(response, request$, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Get an ApiEndpoint.
     */
    async getApiEndpoint(
        apiID: string,
        versionID: string,
        apiEndpointID: string,
        options?: RequestOptions
    ): Promise<operations.GetApiEndpointResponse> {
        const input$: operations.GetApiEndpointRequest = {
            apiID: apiID,
            versionID: versionID,
            apiEndpointID: apiEndpointID,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.GetApiEndpointRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            apiEndpointID: encodeSimple$("apiEndpointID", payload$.apiEndpointID, {
                explode: false,
                charEncoding: "percent",
            }),
            apiID: encodeSimple$("apiID", payload$.apiID, {
                explode: false,
                charEncoding: "percent",
            }),
            versionID: encodeSimple$("versionID", payload$.versionID, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent(
            "/v1/apis/{apiID}/version/{versionID}/api_endpoints/{apiEndpointID}"
        )(pathParams$);

        const query$ = "";

        const security$ =
            typeof this.options$.security === "function"
                ? await this.options$.security()
                : this.options$.security;

        const context = {
            operationID: "getApiEndpoint",
            oAuth2Scopes: [],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = { context, errorCodes: ["4XX", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const responseFields$ = {
            HttpMeta: { Response: response, Request: request$ },
        };

        const [result$] = await this.matcher<operations.GetApiEndpointResponse>()
            .json(200, operations.GetApiEndpointResponse$, { key: "ApiEndpoint" })
            .fail(["4XX", "5XX"])
            .json("default", operations.GetApiEndpointResponse$, { key: "Error" })
            .match(response, request$, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Upsert an ApiEndpoint.
     *
     * @remarks
     * Upsert an ApiEndpoint. If the ApiEndpoint does not exist it will be created, otherwise it will be updated.
     */
    async upsertApiEndpoint(
        apiID: string,
        versionID: string,
        apiEndpointID: string,
        apiEndpoint: components.ApiEndpointInput,
        options?: RequestOptions
    ): Promise<operations.UpsertApiEndpointResponse> {
        const input$: operations.UpsertApiEndpointRequest = {
            apiID: apiID,
            versionID: versionID,
            apiEndpointID: apiEndpointID,
            apiEndpoint: apiEndpoint,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Content-Type", "application/json");
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.UpsertApiEndpointRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = encodeJSON$("body", payload$.ApiEndpoint, { explode: true });

        const pathParams$ = {
            apiEndpointID: encodeSimple$("apiEndpointID", payload$.apiEndpointID, {
                explode: false,
                charEncoding: "percent",
            }),
            apiID: encodeSimple$("apiID", payload$.apiID, {
                explode: false,
                charEncoding: "percent",
            }),
            versionID: encodeSimple$("versionID", payload$.versionID, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent(
            "/v1/apis/{apiID}/version/{versionID}/api_endpoints/{apiEndpointID}"
        )(pathParams$);

        const query$ = "";

        const security$ =
            typeof this.options$.security === "function"
                ? await this.options$.security()
                : this.options$.security;

        const context = {
            operationID: "upsertApiEndpoint",
            oAuth2Scopes: [],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = { context, errorCodes: ["4XX", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "PUT",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const responseFields$ = {
            HttpMeta: { Response: response, Request: request$ },
        };

        const [result$] = await this.matcher<operations.UpsertApiEndpointResponse>()
            .json(200, operations.UpsertApiEndpointResponse$, { key: "ApiEndpoint" })
            .fail(["4XX", "5XX"])
            .json("default", operations.UpsertApiEndpointResponse$, { key: "Error" })
            .match(response, request$, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Generate an OpenAPI specification for a particular ApiEndpoint.
     *
     * @remarks
     * This endpoint will generate a new operation in any registered OpenAPI document if the operation does not already exist in the document.
     * Returns the original document and the newly generated document allowing a diff to be performed to see what has changed.
     */
    async generateOpenApiSpecForApiEndpoint(
        apiID: string,
        versionID: string,
        apiEndpointID: string,
        options?: RequestOptions
    ): Promise<operations.GenerateOpenApiSpecForApiEndpointResponse> {
        const input$: operations.GenerateOpenApiSpecForApiEndpointRequest = {
            apiID: apiID,
            versionID: versionID,
            apiEndpointID: apiEndpointID,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input$,
            (value$) =>
                operations.GenerateOpenApiSpecForApiEndpointRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            apiEndpointID: encodeSimple$("apiEndpointID", payload$.apiEndpointID, {
                explode: false,
                charEncoding: "percent",
            }),
            apiID: encodeSimple$("apiID", payload$.apiID, {
                explode: false,
                charEncoding: "percent",
            }),
            versionID: encodeSimple$("versionID", payload$.versionID, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent(
            "/v1/apis/{apiID}/version/{versionID}/api_endpoints/{apiEndpointID}/generate/openapi"
        )(pathParams$);

        const query$ = "";

        const security$ =
            typeof this.options$.security === "function"
                ? await this.options$.security()
                : this.options$.security;

        const context = {
            operationID: "generateOpenApiSpecForApiEndpoint",
            oAuth2Scopes: [],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = { context, errorCodes: ["4XX", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const responseFields$ = {
            HttpMeta: { Response: response, Request: request$ },
        };

        const [result$] = await this.matcher<operations.GenerateOpenApiSpecForApiEndpointResponse>()
            .json(200, operations.GenerateOpenApiSpecForApiEndpointResponse$, {
                key: "GenerateOpenApiSpecDiff",
            })
            .fail(["4XX", "5XX"])
            .json("default", operations.GenerateOpenApiSpecForApiEndpointResponse$, {
                key: "Error",
            })
            .match(response, request$, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Generate a Postman collection for a particular ApiEndpoint.
     *
     * @remarks
     * Generates a postman collection that allows the endpoint to be called from postman variables produced for any path/query/header parameters included in the OpenAPI document.
     */
    async generatePostmanCollectionForApiEndpoint(
        apiID: string,
        versionID: string,
        apiEndpointID: string,
        options?: RequestOptions & {
            acceptHeaderOverride?: GeneratePostmanCollectionForApiEndpointAcceptEnum;
        }
    ): Promise<operations.GeneratePostmanCollectionForApiEndpointResponse> {
        const input$: operations.GeneratePostmanCollectionForApiEndpointRequest = {
            apiID: apiID,
            versionID: versionID,
            apiEndpointID: apiEndpointID,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);

        const accept =
            options?.acceptHeaderOverride || "application/json;q=1, application/octet-stream;q=0";
        headers$.set("Accept", accept);

        const payload$ = schemas$.parse(
            input$,
            (value$) =>
                operations.GeneratePostmanCollectionForApiEndpointRequest$.outboundSchema.parse(
                    value$
                ),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            apiEndpointID: encodeSimple$("apiEndpointID", payload$.apiEndpointID, {
                explode: false,
                charEncoding: "percent",
            }),
            apiID: encodeSimple$("apiID", payload$.apiID, {
                explode: false,
                charEncoding: "percent",
            }),
            versionID: encodeSimple$("versionID", payload$.versionID, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent(
            "/v1/apis/{apiID}/version/{versionID}/api_endpoints/{apiEndpointID}/generate/postman"
        )(pathParams$);

        const query$ = "";

        const security$ =
            typeof this.options$.security === "function"
                ? await this.options$.security()
                : this.options$.security;

        const context = {
            operationID: "generatePostmanCollectionForApiEndpoint",
            oAuth2Scopes: [],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = { context, errorCodes: ["4XX", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const responseFields$ = {
            HttpMeta: { Response: response, Request: request$ },
        };

        const [result$] =
            await this.matcher<operations.GeneratePostmanCollectionForApiEndpointResponse>()
                .stream(200, operations.GeneratePostmanCollectionForApiEndpointResponse$, {
                    key: "PostmanCollection",
                })
                .fail(["4XX", "5XX"])
                .json("default", operations.GeneratePostmanCollectionForApiEndpointResponse$, {
                    key: "Error",
                })
                .match(response, request$, { extraFields: responseFields$ });

        return result$;
    }
}
