/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  artifactsGetBlob,
  GetBlobAcceptEnum,
} from "../funcs/artifactsGetBlob.js";
import {
  artifactsGetManifest,
  GetManifestAcceptEnum,
} from "../funcs/artifactsGetManifest.js";
import { artifactsGetNamespaces } from "../funcs/artifactsGetNamespaces.js";
import { artifactsGetOASSummary } from "../funcs/artifactsGetOASSummary.js";
import { artifactsGetRevisions } from "../funcs/artifactsGetRevisions.js";
import { artifactsGetTags } from "../funcs/artifactsGetTags.js";
import { artifactsPostTags } from "../funcs/artifactsPostTags.js";
import { artifactsPreflight } from "../funcs/artifactsPreflight.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export { GetManifestAcceptEnum } from "../funcs/artifactsGetManifest.js";

export { GetBlobAcceptEnum } from "../funcs/artifactsGetBlob.js";

export class Artifacts extends ClientSDK {
  /**
   * Get access token for communicating with OCI distribution endpoints
   */
  async preflight(
    request?: components.PreflightRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.PreflightResponse> {
    return unwrapAsync(artifactsPreflight(
      this,
      request,
      options,
    ));
  }

  /**
   * Each namespace contains many revisions.
   */
  async getNamespaces(
    options?: RequestOptions,
  ): Promise<operations.GetNamespacesResponse> {
    return unwrapAsync(artifactsGetNamespaces(
      this,
      options,
    ));
  }

  async getRevisions(
    namespaceName: string,
    nextPageToken?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetRevisionsResponse> {
    return unwrapAsync(artifactsGetRevisions(
      this,
      namespaceName,
      nextPageToken,
      options,
    ));
  }

  async getOASSummary(
    namespaceName: string,
    revisionReference: string,
    options?: RequestOptions,
  ): Promise<operations.GetOASSummaryResponse> {
    return unwrapAsync(artifactsGetOASSummary(
      this,
      namespaceName,
      revisionReference,
      options,
    ));
  }

  async getTags(
    namespaceName: string,
    options?: RequestOptions,
  ): Promise<operations.GetTagsResponse> {
    return unwrapAsync(artifactsGetTags(
      this,
      namespaceName,
      options,
    ));
  }

  /**
   * Add tags to an existing revision
   */
  async postTags(
    namespaceName: string,
    addTags?: components.AddTags | undefined,
    options?: RequestOptions,
  ): Promise<operations.PostTagsResponse> {
    return unwrapAsync(artifactsPostTags(
      this,
      namespaceName,
      addTags,
      options,
    ));
  }

  /**
   * Get manifest for a particular reference
   */
  async getManifest(
    organizationSlug: string,
    workspaceSlug: string,
    namespaceName: string,
    revisionReference: string,
    options?: RequestOptions & { acceptHeaderOverride?: GetManifestAcceptEnum },
  ): Promise<operations.GetManifestResponse> {
    return unwrapAsync(artifactsGetManifest(
      this,
      organizationSlug,
      workspaceSlug,
      namespaceName,
      revisionReference,
      options,
    ));
  }

  /**
   * Get blob for a particular digest
   */
  async getBlob(
    organizationSlug: string,
    workspaceSlug: string,
    namespaceName: string,
    digest: string,
    options?: RequestOptions & { acceptHeaderOverride?: GetBlobAcceptEnum },
  ): Promise<operations.GetBlobResponse> {
    return unwrapAsync(artifactsGetBlob(
      this,
      organizationSlug,
      workspaceSlug,
      namespaceName,
      digest,
      options,
    ));
  }
}
