/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDKHooks } from "../hooks/hooks.js";
import { SDK_METADATA, SDKOptions, serverURLFromOptions } from "../lib/config.js";
import {
    encodeFormQuery as encodeFormQuery$,
    encodeJSON as encodeJSON$,
    encodeSimple as encodeSimple$,
} from "../lib/encodings.js";
import { HTTPClient } from "../lib/http.js";
import * as retries$ from "../lib/retries.js";
import * as schemas$ from "../lib/schemas.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as errors from "../models/errors/index.js";
import * as operations from "../models/operations/index.js";

export class Events extends ClientSDK {
    private readonly options$: SDKOptions & { hooks?: SDKHooks };

    constructor(options: SDKOptions = {}) {
        const opt = options as unknown;
        let hooks: SDKHooks;
        if (
            typeof opt === "object" &&
            opt != null &&
            "hooks" in opt &&
            opt.hooks instanceof SDKHooks
        ) {
            hooks = opt.hooks;
        } else {
            hooks = new SDKHooks();
        }

        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
            hooks,
        });

        this.options$ = { ...options, hooks };
        void this.options$;
    }

    /**
     * Search events for a particular workspace by any field
     */
    async searchWorkspaceEvents(
        request: operations.SearchWorkspaceEventsRequest,
        options?: RequestOptions
    ): Promise<operations.SearchWorkspaceEventsResponse> {
        const input$ = typeof request === "undefined" ? {} : request;
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.SearchWorkspaceEventsRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            workspaceID: encodeSimple$(
                "workspaceID",
                payload$.workspaceID ?? this.options$.workspaceID,
                { explode: false, charEncoding: "percent" }
            ),
        };
        const path$ = this.templateURLComponent("/v1/workspace/{workspaceID}/events")(pathParams$);

        const query$ = encodeFormQuery$({
            generate_gen_lock_id: payload$.generate_gen_lock_id,
            interaction_type: payload$.interaction_type,
            lint_report_digest: payload$.lint_report_digest,
            openapi_diff_report_digest: payload$.openapi_diff_report_digest,
            source_revision_digest: payload$.source_revision_digest,
        });

        const security$ =
            typeof this.options$.security === "function"
                ? await this.options$.security()
                : this.options$.security;

        const context = {
            operationID: "searchWorkspaceEvents",
            oAuth2Scopes: [],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = { context, errorCodes: ["4XX", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const responseFields$ = {
            HttpMeta: { Response: response, Request: request$ },
        };

        const [result$] = await this.matcher<operations.SearchWorkspaceEventsResponse>()
            .json(200, operations.SearchWorkspaceEventsResponse$, { key: "CliEventBatch" })
            .fail("4XX")
            .json("5XX", errors.ErrorT$, { err: true })
            .match(response, request$, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Post events for a specific workspace
     *
     * @remarks
     * Sends an array of events to be stored for a particular workspace.
     */
    async postWorkspaceEvents(
        requestBody: Array<components.CliEvent>,
        workspaceID?: string | undefined,
        options?: RequestOptions & { retries?: retries$.RetryConfig }
    ): Promise<operations.PostWorkspaceEventsResponse> {
        const input$: operations.PostWorkspaceEventsRequest = {
            workspaceID: workspaceID,
            requestBody: requestBody,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Content-Type", "application/json");
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.PostWorkspaceEventsRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = encodeJSON$("body", payload$.RequestBody, { explode: true });

        const pathParams$ = {
            workspaceID: encodeSimple$(
                "workspaceID",
                payload$.workspaceID ?? this.options$.workspaceID,
                { explode: false, charEncoding: "percent" }
            ),
        };
        const path$ = this.templateURLComponent("/v1/workspace/{workspaceID}/events")(pathParams$);

        const query$ = "";

        const security$ =
            typeof this.options$.security === "function"
                ? await this.options$.security()
                : this.options$.security;

        const context = {
            operationID: "postWorkspaceEvents",
            oAuth2Scopes: [],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = { context, errorCodes: ["4XX", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const retryConfig = options?.retries ||
            this.options$.retryConfig || {
                strategy: "backoff",
                backoff: {
                    initialInterval: 100,
                    maxInterval: 2000,
                    exponent: 1.5,
                    maxElapsedTime: 60000,
                },
                retryConnectionErrors: true,
            };

        const response = await retries$.retry(
            () => {
                const cloned = request$.clone();
                return this.do$(cloned, doOptions);
            },
            { config: retryConfig, statusCodes: ["408", "500", "502", "503"] }
        );

        const responseFields$ = {
            HttpMeta: { Response: response, Request: request$ },
        };

        const [result$] = await this.matcher<operations.PostWorkspaceEventsResponse>()
            .void("2XX", operations.PostWorkspaceEventsResponse$)
            .fail("4XX")
            .json("5XX", errors.ErrorT$, { err: true })
            .match(response, request$, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Load recent events for a particular workspace
     */
    async getWorkspaceEventsByTarget(
        targetID: string,
        workspaceID?: string | undefined,
        afterCreatedAt?: Date | undefined,
        options?: RequestOptions
    ): Promise<operations.GetWorkspaceEventsByTargetResponse> {
        const input$: operations.GetWorkspaceEventsByTargetRequest = {
            workspaceID: workspaceID,
            targetID: targetID,
            afterCreatedAt: afterCreatedAt,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.GetWorkspaceEventsByTargetRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            targetID: encodeSimple$("targetID", payload$.targetID, {
                explode: false,
                charEncoding: "percent",
            }),
            workspaceID: encodeSimple$(
                "workspaceID",
                payload$.workspaceID ?? this.options$.workspaceID,
                { explode: false, charEncoding: "percent" }
            ),
        };
        const path$ = this.templateURLComponent(
            "/v1/workspace/{workspaceID}/events/targets/{targetID}/events"
        )(pathParams$);

        const query$ = encodeFormQuery$({
            after_created_at: payload$.after_created_at,
        });

        const security$ =
            typeof this.options$.security === "function"
                ? await this.options$.security()
                : this.options$.security;

        const context = {
            operationID: "getWorkspaceEventsByTarget",
            oAuth2Scopes: [],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = { context, errorCodes: ["4XX", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const responseFields$ = {
            HttpMeta: { Response: response, Request: request$ },
        };

        const [result$] = await this.matcher<operations.GetWorkspaceEventsByTargetResponse>()
            .json(200, operations.GetWorkspaceEventsByTargetResponse$, { key: "CliEventBatch" })
            .fail("4XX")
            .json("5XX", errors.ErrorT$, { err: true })
            .match(response, request$, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Load targets for a particular workspace
     */
    async getWorkspaceTargets(
        workspaceID?: string | undefined,
        afterLastEventCreatedAt?: Date | undefined,
        options?: RequestOptions
    ): Promise<operations.GetWorkspaceTargetsResponse> {
        const input$: operations.GetWorkspaceTargetsRequest = {
            workspaceID: workspaceID,
            afterLastEventCreatedAt: afterLastEventCreatedAt,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.GetWorkspaceTargetsRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            workspaceID: encodeSimple$(
                "workspaceID",
                payload$.workspaceID ?? this.options$.workspaceID,
                { explode: false, charEncoding: "percent" }
            ),
        };
        const path$ = this.templateURLComponent("/v1/workspace/{workspaceID}/events/targets")(
            pathParams$
        );

        const query$ = encodeFormQuery$({
            after_last_event_created_at: payload$.after_last_event_created_at,
        });

        const security$ =
            typeof this.options$.security === "function"
                ? await this.options$.security()
                : this.options$.security;

        const context = {
            operationID: "getWorkspaceTargets",
            oAuth2Scopes: [],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = { context, errorCodes: ["4XX", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const responseFields$ = {
            HttpMeta: { Response: response, Request: request$ },
        };

        const [result$] = await this.matcher<operations.GetWorkspaceTargetsResponse>()
            .json(200, operations.GetWorkspaceTargetsResponse$, { key: "TargetSDKList" })
            .fail("4XX")
            .json("5XX", errors.ErrorT$, { err: true })
            .match(response, request$, { extraFields: responseFields$ });

        return result$;
    }
}
