/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDKHooks } from "../hooks/hooks.js";
import { SDK_METADATA, SDKOptions, serverURLFromOptions } from "../lib/config.js";
import { encodeJSON as encodeJSON$, encodeSimple as encodeSimple$ } from "../lib/encodings.js";
import { HTTPClient } from "../lib/http.js";
import * as schemas$ from "../lib/schemas.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";

export class Metadata extends ClientSDK {
    private readonly options$: SDKOptions & { hooks?: SDKHooks };

    constructor(options: SDKOptions = {}) {
        const opt = options as unknown;
        let hooks: SDKHooks;
        if (
            typeof opt === "object" &&
            opt != null &&
            "hooks" in opt &&
            opt.hooks instanceof SDKHooks
        ) {
            hooks = opt.hooks;
        } else {
            hooks = new SDKHooks();
        }

        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
            hooks,
        });

        this.options$ = { ...options, hooks };
        void this.options$;
    }

    /**
     * Get all metadata for a particular apiID and versionID.
     */
    async getVersionMetadata(
        apiID: string,
        versionID: string,
        options?: RequestOptions
    ): Promise<operations.GetVersionMetadataResponse> {
        const input$: operations.GetVersionMetadataRequest = {
            apiID: apiID,
            versionID: versionID,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.GetVersionMetadataRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            apiID: encodeSimple$("apiID", payload$.apiID, {
                explode: false,
                charEncoding: "percent",
            }),
            versionID: encodeSimple$("versionID", payload$.versionID, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent("/v1/apis/{apiID}/version/{versionID}/metadata")(
            pathParams$
        );

        const query$ = "";

        const security$ =
            typeof this.options$.security === "function"
                ? await this.options$.security()
                : this.options$.security;

        const context = {
            operationID: "getVersionMetadata",
            oAuth2Scopes: [],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = { context, errorCodes: ["4XX", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const responseFields$ = {
            HttpMeta: { Response: response, Request: request$ },
        };

        const [result$] = await this.matcher<operations.GetVersionMetadataResponse>()
            .json(200, operations.GetVersionMetadataResponse$, { key: "VersionMetadata" })
            .fail(["4XX", "5XX"])
            .json("default", operations.GetVersionMetadataResponse$, { key: "Error" })
            .match(response, request$, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Insert metadata for a particular apiID and versionID.
     */
    async insertVersionMetadata(
        apiID: string,
        versionID: string,
        versionMetadata: components.VersionMetadataInput,
        options?: RequestOptions
    ): Promise<operations.InsertVersionMetadataResponse> {
        const input$: operations.InsertVersionMetadataRequest = {
            apiID: apiID,
            versionID: versionID,
            versionMetadata: versionMetadata,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Content-Type", "application/json");
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.InsertVersionMetadataRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = encodeJSON$("body", payload$.VersionMetadata, { explode: true });

        const pathParams$ = {
            apiID: encodeSimple$("apiID", payload$.apiID, {
                explode: false,
                charEncoding: "percent",
            }),
            versionID: encodeSimple$("versionID", payload$.versionID, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent("/v1/apis/{apiID}/version/{versionID}/metadata")(
            pathParams$
        );

        const query$ = "";

        const security$ =
            typeof this.options$.security === "function"
                ? await this.options$.security()
                : this.options$.security;

        const context = {
            operationID: "insertVersionMetadata",
            oAuth2Scopes: [],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = { context, errorCodes: ["4XX", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const responseFields$ = {
            HttpMeta: { Response: response, Request: request$ },
        };

        const [result$] = await this.matcher<operations.InsertVersionMetadataResponse>()
            .json(200, operations.InsertVersionMetadataResponse$, { key: "VersionMetadata" })
            .fail(["4XX", "5XX"])
            .json("default", operations.InsertVersionMetadataResponse$, { key: "Error" })
            .match(response, request$, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Delete metadata for a particular apiID and versionID.
     */
    async deleteVersionMetadata(
        apiID: string,
        versionID: string,
        metaKey: string,
        metaValue: string,
        options?: RequestOptions
    ): Promise<operations.DeleteVersionMetadataResponse> {
        const input$: operations.DeleteVersionMetadataRequest = {
            apiID: apiID,
            versionID: versionID,
            metaKey: metaKey,
            metaValue: metaValue,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.DeleteVersionMetadataRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            apiID: encodeSimple$("apiID", payload$.apiID, {
                explode: false,
                charEncoding: "percent",
            }),
            metaKey: encodeSimple$("metaKey", payload$.metaKey, {
                explode: false,
                charEncoding: "percent",
            }),
            metaValue: encodeSimple$("metaValue", payload$.metaValue, {
                explode: false,
                charEncoding: "percent",
            }),
            versionID: encodeSimple$("versionID", payload$.versionID, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent(
            "/v1/apis/{apiID}/version/{versionID}/metadata/{metaKey}/{metaValue}"
        )(pathParams$);

        const query$ = "";

        const security$ =
            typeof this.options$.security === "function"
                ? await this.options$.security()
                : this.options$.security;

        const context = {
            operationID: "deleteVersionMetadata",
            oAuth2Scopes: [],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = { context, errorCodes: ["4XX", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "DELETE",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const responseFields$ = {
            HttpMeta: { Response: response, Request: request$ },
        };

        const [result$] = await this.matcher<operations.DeleteVersionMetadataResponse>()
            .void(200, operations.DeleteVersionMetadataResponse$)
            .fail(["4XX", "5XX"])
            .json("default", operations.DeleteVersionMetadataResponse$, { key: "Error" })
            .match(response, request$, { extraFields: responseFields$ });

        return result$;
    }
}
