/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { publishingTokensCreate } from "../funcs/publishingTokensCreate.js";
import { publishingTokensDelete } from "../funcs/publishingTokensDelete.js";
import { publishingTokensGet } from "../funcs/publishingTokensGet.js";
import { publishingTokensList } from "../funcs/publishingTokensList.js";
import { publishingTokensResolveMetadata } from "../funcs/publishingTokensResolveMetadata.js";
import { publishingTokensResolveTarget } from "../funcs/publishingTokensResolveTarget.js";
import { publishingTokensUpdate } from "../funcs/publishingTokensUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class PublishingTokens extends ClientSDK {
  /**
   * Get publishing tokens for a workspace
   *
   * @remarks
   * Returns a publishing token for the current workspace
   */
  async list(
    options?: RequestOptions,
  ): Promise<operations.GetPublishingTokenResponse> {
    return unwrapAsync(publishingTokensList(
      this,
      options,
    ));
  }

  /**
   * Create a publishing token for a workspace
   *
   * @remarks
   * Creates a publishing token for the current workspace
   */
  async create(
    request?: operations.CreatePublishingTokenRequestBody | undefined,
    options?: RequestOptions,
  ): Promise<operations.CreatePublishingTokenResponse> {
    return unwrapAsync(publishingTokensCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a specific publishing token
   *
   * @remarks
   * Get information about a particular publishing token.
   */
  async get(
    tokenID: string,
    options?: RequestOptions,
  ): Promise<operations.GetPublishingTokenByIDResponse> {
    return unwrapAsync(publishingTokensGet(
      this,
      tokenID,
      options,
    ));
  }

  /**
   * Updates the validitity period of a publishing token
   *
   * @remarks
   * Updates the validity period of a particular publishing token.
   */
  async update(
    tokenID: string,
    requestBody?:
      | operations.UpdatePublishingTokenExpirationRequestBody
      | undefined,
    options?: RequestOptions,
  ): Promise<operations.UpdatePublishingTokenExpirationResponse> {
    return unwrapAsync(publishingTokensUpdate(
      this,
      tokenID,
      requestBody,
      options,
    ));
  }

  /**
   * Delete a specific publishing token
   *
   * @remarks
   * Delete a particular publishing token.
   */
  async delete(
    tokenID: string,
    options?: RequestOptions,
  ): Promise<operations.DeletePublishingTokenResponse> {
    return unwrapAsync(publishingTokensDelete(
      this,
      tokenID,
      options,
    ));
  }

  /**
   * Get a specific publishing token target
   *
   * @remarks
   * Get information about a particular publishing token target.
   */
  async resolveTarget(
    tokenID: string,
    options?: RequestOptions,
  ): Promise<operations.GetPublishingTokenTargetByIDResponse> {
    return unwrapAsync(publishingTokensResolveTarget(
      this,
      tokenID,
      options,
    ));
  }

  /**
   * Get metadata about the token
   *
   * @remarks
   * Get information about a particular publishing token.
   */
  async resolveMetadata(
    tokenID: string,
    options?: RequestOptions,
  ): Promise<operations.GetPublishingTokenPublicMetadataResponse> {
    return unwrapAsync(publishingTokensResolveMetadata(
      this,
      tokenID,
      options,
    ));
  }
}
