/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDKHooks } from "../hooks/hooks.js";
import { SDK_METADATA, SDKOptions, serverURLFromOptions } from "../lib/config.js";
import {
    encodeFormQuery as encodeFormQuery$,
    encodeJSON as encodeJSON$,
    encodeSimple as encodeSimple$,
} from "../lib/encodings.js";
import { HTTPClient } from "../lib/http.js";
import * as schemas$ from "../lib/schemas.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { isBlobLike } from "../types/blobs.js";

export enum ApplyOperationIDsAcceptEnum {
    applicationJson = "application/json",
    applicationXYaml = "application/x-yaml",
}

export class Suggest extends ClientSDK {
    private readonly options$: SDKOptions & { hooks?: SDKHooks };

    constructor(options: SDKOptions = {}) {
        const opt = options as unknown;
        let hooks: SDKHooks;
        if (
            typeof opt === "object" &&
            opt != null &&
            "hooks" in opt &&
            opt.hooks instanceof SDKHooks
        ) {
            hooks = opt.hooks;
        } else {
            hooks = new SDKHooks();
        }

        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
            hooks,
        });

        this.options$ = { ...options, hooks };
        void this.options$;
    }

    /**
     * Generate operation ID suggestions.
     *
     * @remarks
     * Get suggestions from an LLM model for improving the operationIDs in the provided schema.
     */
    async suggestOperationIDs(
        xSessionId: string,
        requestBody: operations.SuggestOperationIDsRequestBody,
        limit?: number | undefined,
        options?: RequestOptions
    ): Promise<operations.SuggestOperationIDsResponse> {
        const input$: operations.SuggestOperationIDsRequest = {
            xSessionId: xSessionId,
            limit: limit,
            requestBody: requestBody,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.SuggestOperationIDsRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = new FormData();

        if (isBlobLike(payload$.RequestBody.schema)) {
            body$.append("schema", payload$.RequestBody.schema);
        } else {
            body$.append(
                "schema",
                new Blob([payload$.RequestBody.schema.content], {
                    type: "application/octet-stream",
                }),
                payload$.RequestBody.schema.fileName
            );
        }
        if (payload$.RequestBody.opts !== undefined) {
            body$.append("opts", encodeJSON$("opts", payload$.RequestBody.opts, { explode: true }));
        }

        const path$ = this.templateURLComponent("/v1/suggest/operation_ids")();

        const query$ = encodeFormQuery$({
            limit: payload$.limit,
        });

        headers$.set(
            "x-session-id",
            encodeSimple$("x-session-id", payload$["x-session-id"], {
                explode: false,
                charEncoding: "none",
            })
        );

        const security$ =
            typeof this.options$.security === "function"
                ? await this.options$.security()
                : this.options$.security;

        const context = {
            operationID: "suggestOperationIDs",
            oAuth2Scopes: [],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = { context, errorCodes: ["4XX", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const responseFields$ = {
            HttpMeta: { Response: response, Request: request$ },
        };

        const [result$] = await this.matcher<operations.SuggestOperationIDsResponse>()
            .json(200, operations.SuggestOperationIDsResponse$, { key: "SuggestedOperationIDs" })
            .fail(["4XX", "5XX"])
            .match(response, request$, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Generate operation ID suggestions.
     *
     * @remarks
     * Get suggestions from an LLM model for improving the operationIDs in the provided schema.
     */
    async suggestOperationIDsRegistry(
        request: operations.SuggestOperationIDsRegistryRequest,
        options?: RequestOptions
    ): Promise<operations.SuggestOperationIDsRegistryResponse> {
        const input$ = request;
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Content-Type", "application/json");
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.SuggestOperationIDsRegistryRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = encodeJSON$("body", payload$.SuggestOperationIDsOpts, { explode: true });

        const pathParams$ = {
            namespace_name: encodeSimple$("namespace_name", payload$.namespace_name, {
                explode: false,
                charEncoding: "percent",
            }),
            revision_reference: encodeSimple$("revision_reference", payload$.revision_reference, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent(
            "/v1/suggest/operation_ids/{namespace_name}/{revision_reference}"
        )(pathParams$);

        const query$ = encodeFormQuery$({
            limit: payload$.limit,
        });

        headers$.set(
            "x-session-id",
            encodeSimple$("x-session-id", payload$["x-session-id"], {
                explode: false,
                charEncoding: "none",
            })
        );

        const security$ =
            typeof this.options$.security === "function"
                ? await this.options$.security()
                : this.options$.security;

        const context = {
            operationID: "suggestOperationIDsRegistry",
            oAuth2Scopes: [],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = { context, errorCodes: ["4XX", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const responseFields$ = {
            HttpMeta: { Response: response, Request: request$ },
        };

        const [result$] = await this.matcher<operations.SuggestOperationIDsRegistryResponse>()
            .json(200, operations.SuggestOperationIDsRegistryResponse$, {
                key: "SuggestedOperationIDs",
            })
            .fail(["4XX", "5XX"])
            .match(response, request$, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Apply operation ID suggestions and download result.
     */
    async applyOperationIDs(
        xSessionId: string,
        requestBody?: operations.ApplyOperationIDsRequestBody | undefined,
        options?: RequestOptions & { acceptHeaderOverride?: ApplyOperationIDsAcceptEnum }
    ): Promise<operations.ApplyOperationIDsResponse> {
        const input$: operations.ApplyOperationIDsRequest = {
            xSessionId: xSessionId,
            requestBody: requestBody,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Content-Type", "application/json");

        const accept =
            options?.acceptHeaderOverride || "application/json;q=1, application/x-yaml;q=0";
        headers$.set("Accept", accept);

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.ApplyOperationIDsRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = encodeJSON$("body", payload$.RequestBody, { explode: true });

        const path$ = this.templateURLComponent("/v1/suggest/operation_ids/apply")();

        const query$ = "";

        headers$.set(
            "x-session-id",
            encodeSimple$("x-session-id", payload$["x-session-id"], {
                explode: false,
                charEncoding: "none",
            })
        );

        const security$ =
            typeof this.options$.security === "function"
                ? await this.options$.security()
                : this.options$.security;

        const context = {
            operationID: "applyOperationIDs",
            oAuth2Scopes: [],
            securitySource: this.options$.security,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = { context, errorCodes: ["4XX", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const responseFields$ = {
            HttpMeta: { Response: response, Request: request$ },
        };

        const [result$] = await this.matcher<operations.ApplyOperationIDsResponse>()
            .stream(200, operations.ApplyOperationIDsResponse$, {
                ctype: "application/json",
                key: "200_application/json_Schema",
            })
            .stream(200, operations.ApplyOperationIDsResponse$, {
                ctype: "application/x-yaml",
                key: "200_application/x-yaml_Schema",
            })
            .fail(["4XX", "5XX"])
            .json("default", operations.ApplyOperationIDsResponse$, { key: "Error" })
            .match(response, request$, { extraFields: responseFields$ });

        return result$;
    }
}
