/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the petstore SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx authValidateApiKey.example.ts
 */

import { SDK } from "petstore";

const sdk = new SDK({
  security: {
    apiKey: "<YOUR_API_KEY_HERE>",
  },
});

async function main() {
  const result = await sdk.auth.validateApiKey();

  console.log(result);
}

main().catch(console.error);
