/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

/**
 * Apply options
 */
export type ApplyOperationIDsRequestBody = {
    /**
     * Whether to apply the suggestions as an overlay or replace the existing operationIDs. Default: false
     */
    asOverlay?: boolean | undefined;
};

export type ApplyOperationIDsRequest = {
    xSessionId: string;
    /**
     * Apply options
     */
    requestBody?: ApplyOperationIDsRequestBody | undefined;
};

export type ApplyOperationIDsResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    twoHundredApplicationJsonSchema?: ReadableStream<Uint8Array> | undefined;
    /**
     * OK
     */
    twoHundredApplicationXYamlSchema?: ReadableStream<Uint8Array> | undefined;
    /**
     * Default error response
     */
    error?: errors.ErrorT | undefined;
};

/** @internal */
export namespace ApplyOperationIDsRequestBody$ {
    export const inboundSchema: z.ZodType<ApplyOperationIDsRequestBody, z.ZodTypeDef, unknown> = z
        .object({
            as_overlay: z.boolean().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                as_overlay: "asOverlay",
            });
        });

    export type Outbound = {
        as_overlay?: boolean | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ApplyOperationIDsRequestBody> = z
        .object({
            asOverlay: z.boolean().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                asOverlay: "as_overlay",
            });
        });
}

/** @internal */
export namespace ApplyOperationIDsRequest$ {
    export const inboundSchema: z.ZodType<ApplyOperationIDsRequest, z.ZodTypeDef, unknown> = z
        .object({
            "x-session-id": z.string(),
            RequestBody: z.lazy(() => ApplyOperationIDsRequestBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return remap$(v, {
                "x-session-id": "xSessionId",
                RequestBody: "requestBody",
            });
        });

    export type Outbound = {
        "x-session-id": string;
        RequestBody?: ApplyOperationIDsRequestBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ApplyOperationIDsRequest> = z
        .object({
            xSessionId: z.string(),
            requestBody: z.lazy(() => ApplyOperationIDsRequestBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return remap$(v, {
                xSessionId: "x-session-id",
                requestBody: "RequestBody",
            });
        });
}

/** @internal */
export namespace ApplyOperationIDsResponse$ {
    export const inboundSchema: z.ZodType<ApplyOperationIDsResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            "200_application/json_Schema": z.instanceof(ReadableStream<Uint8Array>).optional(),
            "200_application/x-yaml_Schema": z.instanceof(ReadableStream<Uint8Array>).optional(),
            Error: errors.ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                "200_application/json_Schema": "twoHundredApplicationJsonSchema",
                "200_application/x-yaml_Schema": "twoHundredApplicationXYamlSchema",
                Error: "error",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        "200_application/json_Schema"?: ReadableStream<Uint8Array> | undefined;
        "200_application/x-yaml_Schema"?: ReadableStream<Uint8Array> | undefined;
        Error?: errors.ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ApplyOperationIDsResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            twoHundredApplicationJsonSchema: z.instanceof(ReadableStream<Uint8Array>).optional(),
            twoHundredApplicationXYamlSchema: z.instanceof(ReadableStream<Uint8Array>).optional(),
            error: errors.ErrorT$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                twoHundredApplicationJsonSchema: "200_application/json_Schema",
                twoHundredApplicationXYamlSchema: "200_application/x-yaml_Schema",
                error: "Error",
            });
        });
}
