/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as errors from "../errors/index.js";

export type ConfigureCodeSamplesResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  githubConfigureCodeSamplesResponse?:
    | components.GithubConfigureCodeSamplesResponse
    | undefined;
  /**
   * Default error response
   */
  error?: errors.ErrorT | undefined;
};

/** @internal */
export const ConfigureCodeSamplesResponse$inboundSchema: z.ZodType<
  ConfigureCodeSamplesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  GithubConfigureCodeSamplesResponse: components
    .GithubConfigureCodeSamplesResponse$inboundSchema.optional(),
  Error: errors.ErrorT$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "GithubConfigureCodeSamplesResponse": "githubConfigureCodeSamplesResponse",
    "Error": "error",
  });
});

/** @internal */
export type ConfigureCodeSamplesResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  GithubConfigureCodeSamplesResponse?:
    | components.GithubConfigureCodeSamplesResponse$Outbound
    | undefined;
  Error?: errors.ErrorT$Outbound | undefined;
};

/** @internal */
export const ConfigureCodeSamplesResponse$outboundSchema: z.ZodType<
  ConfigureCodeSamplesResponse$Outbound,
  z.ZodTypeDef,
  ConfigureCodeSamplesResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  githubConfigureCodeSamplesResponse: components
    .GithubConfigureCodeSamplesResponse$outboundSchema.optional(),
  error: errors.ErrorT$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    githubConfigureCodeSamplesResponse: "GithubConfigureCodeSamplesResponse",
    error: "Error",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConfigureCodeSamplesResponse$ {
  /** @deprecated use `ConfigureCodeSamplesResponse$inboundSchema` instead. */
  export const inboundSchema = ConfigureCodeSamplesResponse$inboundSchema;
  /** @deprecated use `ConfigureCodeSamplesResponse$outboundSchema` instead. */
  export const outboundSchema = ConfigureCodeSamplesResponse$outboundSchema;
  /** @deprecated use `ConfigureCodeSamplesResponse$Outbound` instead. */
  export type Outbound = ConfigureCodeSamplesResponse$Outbound;
}
