/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as errors from "../errors/index.js";

export type ConfigureMintlifyRepoResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Default error response
   */
  error?: errors.ErrorT | undefined;
};

/** @internal */
export const ConfigureMintlifyRepoResponse$inboundSchema: z.ZodType<
  ConfigureMintlifyRepoResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  Error: errors.ErrorT$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "Error": "error",
  });
});

/** @internal */
export type ConfigureMintlifyRepoResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  Error?: errors.ErrorT$Outbound | undefined;
};

/** @internal */
export const ConfigureMintlifyRepoResponse$outboundSchema: z.ZodType<
  ConfigureMintlifyRepoResponse$Outbound,
  z.ZodTypeDef,
  ConfigureMintlifyRepoResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  error: errors.ErrorT$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    error: "Error",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConfigureMintlifyRepoResponse$ {
  /** @deprecated use `ConfigureMintlifyRepoResponse$inboundSchema` instead. */
  export const inboundSchema = ConfigureMintlifyRepoResponse$inboundSchema;
  /** @deprecated use `ConfigureMintlifyRepoResponse$outboundSchema` instead. */
  export const outboundSchema = ConfigureMintlifyRepoResponse$outboundSchema;
  /** @deprecated use `ConfigureMintlifyRepoResponse$Outbound` instead. */
  export type Outbound = ConfigureMintlifyRepoResponse$Outbound;
}
