/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateRemoteSourceResponse = {
  httpMeta: components.HTTPMetadata;
};

/** @internal */
export const CreateRemoteSourceResponse$inboundSchema: z.ZodType<
  CreateRemoteSourceResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
  });
});

/** @internal */
export type CreateRemoteSourceResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
};

/** @internal */
export const CreateRemoteSourceResponse$outboundSchema: z.ZodType<
  CreateRemoteSourceResponse$Outbound,
  z.ZodTypeDef,
  CreateRemoteSourceResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateRemoteSourceResponse$ {
  /** @deprecated use `CreateRemoteSourceResponse$inboundSchema` instead. */
  export const inboundSchema = CreateRemoteSourceResponse$inboundSchema;
  /** @deprecated use `CreateRemoteSourceResponse$outboundSchema` instead. */
  export const outboundSchema = CreateRemoteSourceResponse$outboundSchema;
  /** @deprecated use `CreateRemoteSourceResponse$Outbound` instead. */
  export type Outbound = CreateRemoteSourceResponse$Outbound;
}

export function createRemoteSourceResponseToJSON(
  createRemoteSourceResponse: CreateRemoteSourceResponse,
): string {
  return JSON.stringify(
    CreateRemoteSourceResponse$outboundSchema.parse(createRemoteSourceResponse),
  );
}

export function createRemoteSourceResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateRemoteSourceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateRemoteSourceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateRemoteSourceResponse' from JSON`,
  );
}
