/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type CreateFreeTrialResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Default error response
     */
    error?: errors.ErrorT | undefined;
};

/** @internal */
export namespace CreateFreeTrialResponse$ {
    export const inboundSchema: z.ZodType<CreateFreeTrialResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            Error: errors.ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                Error: "error",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Error?: errors.ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateFreeTrialResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            error: errors.ErrorT$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                error: "Error",
            });
        });
}
