/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateWorkspaceTokenGlobals = {
  workspaceId?: string | undefined;
};

export type CreateWorkspaceTokenRequest = {
  /**
   * Unique identifier of the workspace.
   */
  workspaceId?: string | undefined;
  workspaceToken: components.WorkspaceToken;
};

export type CreateWorkspaceTokenResponse = {
  httpMeta: components.HTTPMetadata;
};

/** @internal */
export const CreateWorkspaceTokenGlobals$inboundSchema: z.ZodType<
  CreateWorkspaceTokenGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  workspace_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "workspace_id": "workspaceId",
  });
});

/** @internal */
export type CreateWorkspaceTokenGlobals$Outbound = {
  workspace_id?: string | undefined;
};

/** @internal */
export const CreateWorkspaceTokenGlobals$outboundSchema: z.ZodType<
  CreateWorkspaceTokenGlobals$Outbound,
  z.ZodTypeDef,
  CreateWorkspaceTokenGlobals
> = z.object({
  workspaceId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    workspaceId: "workspace_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateWorkspaceTokenGlobals$ {
  /** @deprecated use `CreateWorkspaceTokenGlobals$inboundSchema` instead. */
  export const inboundSchema = CreateWorkspaceTokenGlobals$inboundSchema;
  /** @deprecated use `CreateWorkspaceTokenGlobals$outboundSchema` instead. */
  export const outboundSchema = CreateWorkspaceTokenGlobals$outboundSchema;
  /** @deprecated use `CreateWorkspaceTokenGlobals$Outbound` instead. */
  export type Outbound = CreateWorkspaceTokenGlobals$Outbound;
}

export function createWorkspaceTokenGlobalsToJSON(
  createWorkspaceTokenGlobals: CreateWorkspaceTokenGlobals,
): string {
  return JSON.stringify(
    CreateWorkspaceTokenGlobals$outboundSchema.parse(
      createWorkspaceTokenGlobals,
    ),
  );
}

export function createWorkspaceTokenGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<CreateWorkspaceTokenGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWorkspaceTokenGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWorkspaceTokenGlobals' from JSON`,
  );
}

/** @internal */
export const CreateWorkspaceTokenRequest$inboundSchema: z.ZodType<
  CreateWorkspaceTokenRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  workspace_id: z.string().optional(),
  WorkspaceToken: components.WorkspaceToken$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "workspace_id": "workspaceId",
    "WorkspaceToken": "workspaceToken",
  });
});

/** @internal */
export type CreateWorkspaceTokenRequest$Outbound = {
  workspace_id?: string | undefined;
  WorkspaceToken: components.WorkspaceToken$Outbound;
};

/** @internal */
export const CreateWorkspaceTokenRequest$outboundSchema: z.ZodType<
  CreateWorkspaceTokenRequest$Outbound,
  z.ZodTypeDef,
  CreateWorkspaceTokenRequest
> = z.object({
  workspaceId: z.string().optional(),
  workspaceToken: components.WorkspaceToken$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    workspaceId: "workspace_id",
    workspaceToken: "WorkspaceToken",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateWorkspaceTokenRequest$ {
  /** @deprecated use `CreateWorkspaceTokenRequest$inboundSchema` instead. */
  export const inboundSchema = CreateWorkspaceTokenRequest$inboundSchema;
  /** @deprecated use `CreateWorkspaceTokenRequest$outboundSchema` instead. */
  export const outboundSchema = CreateWorkspaceTokenRequest$outboundSchema;
  /** @deprecated use `CreateWorkspaceTokenRequest$Outbound` instead. */
  export type Outbound = CreateWorkspaceTokenRequest$Outbound;
}

export function createWorkspaceTokenRequestToJSON(
  createWorkspaceTokenRequest: CreateWorkspaceTokenRequest,
): string {
  return JSON.stringify(
    CreateWorkspaceTokenRequest$outboundSchema.parse(
      createWorkspaceTokenRequest,
    ),
  );
}

export function createWorkspaceTokenRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateWorkspaceTokenRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWorkspaceTokenRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWorkspaceTokenRequest' from JSON`,
  );
}

/** @internal */
export const CreateWorkspaceTokenResponse$inboundSchema: z.ZodType<
  CreateWorkspaceTokenResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
  });
});

/** @internal */
export type CreateWorkspaceTokenResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
};

/** @internal */
export const CreateWorkspaceTokenResponse$outboundSchema: z.ZodType<
  CreateWorkspaceTokenResponse$Outbound,
  z.ZodTypeDef,
  CreateWorkspaceTokenResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateWorkspaceTokenResponse$ {
  /** @deprecated use `CreateWorkspaceTokenResponse$inboundSchema` instead. */
  export const inboundSchema = CreateWorkspaceTokenResponse$inboundSchema;
  /** @deprecated use `CreateWorkspaceTokenResponse$outboundSchema` instead. */
  export const outboundSchema = CreateWorkspaceTokenResponse$outboundSchema;
  /** @deprecated use `CreateWorkspaceTokenResponse$Outbound` instead. */
  export type Outbound = CreateWorkspaceTokenResponse$Outbound;
}

export function createWorkspaceTokenResponseToJSON(
  createWorkspaceTokenResponse: CreateWorkspaceTokenResponse,
): string {
  return JSON.stringify(
    CreateWorkspaceTokenResponse$outboundSchema.parse(
      createWorkspaceTokenResponse,
    ),
  );
}

export function createWorkspaceTokenResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateWorkspaceTokenResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWorkspaceTokenResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWorkspaceTokenResponse' from JSON`,
  );
}
