/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The format of the OpenAPI specification.
 */
export enum Format {
  Json = "json",
  Yaml = "yaml",
}

export type CreateSchemaStoreItemRequestBody = {
  /**
   * The OpenAPI specification to store.
   */
  spec: string;
  /**
   * The package name to use in code snippets / quickstart.
   */
  packageName: string;
  /**
   * The classname of the SDK to use in code snippets / quickstart.
   */
  sdkClassname: string;
  /**
   * The format of the OpenAPI specification.
   */
  format: Format;
};

export type CreateSchemaStoreItemResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  schemaStoreItem?: components.SchemaStoreItem | undefined;
};

/** @internal */
export const Format$inboundSchema: z.ZodNativeEnum<typeof Format> = z
  .nativeEnum(Format);

/** @internal */
export const Format$outboundSchema: z.ZodNativeEnum<typeof Format> =
  Format$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Format$ {
  /** @deprecated use `Format$inboundSchema` instead. */
  export const inboundSchema = Format$inboundSchema;
  /** @deprecated use `Format$outboundSchema` instead. */
  export const outboundSchema = Format$outboundSchema;
}

/** @internal */
export const CreateSchemaStoreItemRequestBody$inboundSchema: z.ZodType<
  CreateSchemaStoreItemRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  spec: z.string(),
  packageName: z.string(),
  sdkClassname: z.string(),
  format: Format$inboundSchema,
});

/** @internal */
export type CreateSchemaStoreItemRequestBody$Outbound = {
  spec: string;
  packageName: string;
  sdkClassname: string;
  format: string;
};

/** @internal */
export const CreateSchemaStoreItemRequestBody$outboundSchema: z.ZodType<
  CreateSchemaStoreItemRequestBody$Outbound,
  z.ZodTypeDef,
  CreateSchemaStoreItemRequestBody
> = z.object({
  spec: z.string(),
  packageName: z.string(),
  sdkClassname: z.string(),
  format: Format$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateSchemaStoreItemRequestBody$ {
  /** @deprecated use `CreateSchemaStoreItemRequestBody$inboundSchema` instead. */
  export const inboundSchema = CreateSchemaStoreItemRequestBody$inboundSchema;
  /** @deprecated use `CreateSchemaStoreItemRequestBody$outboundSchema` instead. */
  export const outboundSchema = CreateSchemaStoreItemRequestBody$outboundSchema;
  /** @deprecated use `CreateSchemaStoreItemRequestBody$Outbound` instead. */
  export type Outbound = CreateSchemaStoreItemRequestBody$Outbound;
}

export function createSchemaStoreItemRequestBodyToJSON(
  createSchemaStoreItemRequestBody: CreateSchemaStoreItemRequestBody,
): string {
  return JSON.stringify(
    CreateSchemaStoreItemRequestBody$outboundSchema.parse(
      createSchemaStoreItemRequestBody,
    ),
  );
}

export function createSchemaStoreItemRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateSchemaStoreItemRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateSchemaStoreItemRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateSchemaStoreItemRequestBody' from JSON`,
  );
}

/** @internal */
export const CreateSchemaStoreItemResponse$inboundSchema: z.ZodType<
  CreateSchemaStoreItemResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  SchemaStoreItem: components.SchemaStoreItem$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "SchemaStoreItem": "schemaStoreItem",
  });
});

/** @internal */
export type CreateSchemaStoreItemResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  SchemaStoreItem?: components.SchemaStoreItem$Outbound | undefined;
};

/** @internal */
export const CreateSchemaStoreItemResponse$outboundSchema: z.ZodType<
  CreateSchemaStoreItemResponse$Outbound,
  z.ZodTypeDef,
  CreateSchemaStoreItemResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  schemaStoreItem: components.SchemaStoreItem$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    schemaStoreItem: "SchemaStoreItem",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateSchemaStoreItemResponse$ {
  /** @deprecated use `CreateSchemaStoreItemResponse$inboundSchema` instead. */
  export const inboundSchema = CreateSchemaStoreItemResponse$inboundSchema;
  /** @deprecated use `CreateSchemaStoreItemResponse$outboundSchema` instead. */
  export const outboundSchema = CreateSchemaStoreItemResponse$outboundSchema;
  /** @deprecated use `CreateSchemaStoreItemResponse$Outbound` instead. */
  export type Outbound = CreateSchemaStoreItemResponse$Outbound;
}

export function createSchemaStoreItemResponseToJSON(
  createSchemaStoreItemResponse: CreateSchemaStoreItemResponse,
): string {
  return JSON.stringify(
    CreateSchemaStoreItemResponse$outboundSchema.parse(
      createSchemaStoreItemResponse,
    ),
  );
}

export function createSchemaStoreItemResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateSchemaStoreItemResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateSchemaStoreItemResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateSchemaStoreItemResponse' from JSON`,
  );
}
