/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type DownloadSchemaRevisionRequest = {
    /**
     * The ID of the Api to retrieve schemas for.
     */
    apiID: string;
    /**
     * The version ID of the Api to delete metadata for.
     */
    versionID: string;
    /**
     * The revision ID of the schema to retrieve.
     */
    revisionID: string;
};

export type DownloadSchemaRevisionResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    twoHundredApplicationJsonSchema?: ReadableStream<Uint8Array> | undefined;
    /**
     * OK
     */
    twoHundredApplicationXYamlSchema?: ReadableStream<Uint8Array> | undefined;
    /**
     * Default error response
     */
    error?: errors.ErrorT | undefined;
};

/** @internal */
export namespace DownloadSchemaRevisionRequest$ {
    export const inboundSchema: z.ZodType<DownloadSchemaRevisionRequest, z.ZodTypeDef, unknown> =
        z.object({
            apiID: z.string(),
            versionID: z.string(),
            revisionID: z.string(),
        });

    export type Outbound = {
        apiID: string;
        versionID: string;
        revisionID: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DownloadSchemaRevisionRequest> =
        z.object({
            apiID: z.string(),
            versionID: z.string(),
            revisionID: z.string(),
        });
}

/** @internal */
export namespace DownloadSchemaRevisionResponse$ {
    export const inboundSchema: z.ZodType<DownloadSchemaRevisionResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            "200_application/json_Schema": z.instanceof(ReadableStream<Uint8Array>).optional(),
            "200_application/x-yaml_Schema": z.instanceof(ReadableStream<Uint8Array>).optional(),
            Error: errors.ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                "200_application/json_Schema": "twoHundredApplicationJsonSchema",
                "200_application/x-yaml_Schema": "twoHundredApplicationXYamlSchema",
                Error: "error",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        "200_application/json_Schema"?: ReadableStream<Uint8Array> | undefined;
        "200_application/x-yaml_Schema"?: ReadableStream<Uint8Array> | undefined;
        Error?: errors.ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DownloadSchemaRevisionResponse> =
        z
            .object({
                httpMeta: components.HTTPMetadata$.outboundSchema,
                twoHundredApplicationJsonSchema: z
                    .instanceof(ReadableStream<Uint8Array>)
                    .optional(),
                twoHundredApplicationXYamlSchema: z
                    .instanceof(ReadableStream<Uint8Array>)
                    .optional(),
                error: errors.ErrorT$.outboundSchema.optional(),
            })
            .transform((v) => {
                return remap$(v, {
                    httpMeta: "HttpMeta",
                    twoHundredApplicationJsonSchema: "200_application/json_Schema",
                    twoHundredApplicationXYamlSchema: "200_application/x-yaml_Schema",
                    error: "Error",
                });
            });
}
