/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type GenerateOpenApiSpecForApiEndpointRequest = {
    /**
     * The ID of the Api to generate an OpenAPI specification for.
     */
    apiID: string;
    /**
     * The version ID of the Api to generate an OpenAPI specification for.
     */
    versionID: string;
    /**
     * The ID of the ApiEndpoint to generate an OpenAPI specification for.
     */
    apiEndpointID: string;
};

export type GenerateOpenApiSpecForApiEndpointResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    generateOpenApiSpecDiff?: components.GenerateOpenApiSpecDiff | undefined;
    /**
     * Default error response
     */
    error?: errors.ErrorT | undefined;
};

/** @internal */
export namespace GenerateOpenApiSpecForApiEndpointRequest$ {
    export const inboundSchema: z.ZodType<
        GenerateOpenApiSpecForApiEndpointRequest,
        z.ZodTypeDef,
        unknown
    > = z.object({
        apiID: z.string(),
        versionID: z.string(),
        apiEndpointID: z.string(),
    });

    export type Outbound = {
        apiID: string;
        versionID: string;
        apiEndpointID: string;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GenerateOpenApiSpecForApiEndpointRequest
    > = z.object({
        apiID: z.string(),
        versionID: z.string(),
        apiEndpointID: z.string(),
    });
}

/** @internal */
export namespace GenerateOpenApiSpecForApiEndpointResponse$ {
    export const inboundSchema: z.ZodType<
        GenerateOpenApiSpecForApiEndpointResponse,
        z.ZodTypeDef,
        unknown
    > = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            GenerateOpenApiSpecDiff: components.GenerateOpenApiSpecDiff$.inboundSchema.optional(),
            Error: errors.ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                GenerateOpenApiSpecDiff: "generateOpenApiSpecDiff",
                Error: "error",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        GenerateOpenApiSpecDiff?: components.GenerateOpenApiSpecDiff$.Outbound | undefined;
        Error?: errors.ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GenerateOpenApiSpecForApiEndpointResponse
    > = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            generateOpenApiSpecDiff: components.GenerateOpenApiSpecDiff$.outboundSchema.optional(),
            error: errors.ErrorT$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                generateOpenApiSpecDiff: "GenerateOpenApiSpecDiff",
                error: "Error",
            });
        });
}
