/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type GeneratePostmanCollectionForApiEndpointRequest = {
  /**
   * The ID of the Api to generate a Postman collection for.
   */
  apiID: string;
  /**
   * The version ID of the Api to generate a Postman collection for.
   */
  versionID: string;
  /**
   * The ID of the ApiEndpoint to generate a Postman collection for.
   */
  apiEndpointID: string;
};

export type GeneratePostmanCollectionForApiEndpointResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  postmanCollection?: ReadableStream<Uint8Array> | undefined;
};

/** @internal */
export const GeneratePostmanCollectionForApiEndpointRequest$inboundSchema:
  z.ZodType<
    GeneratePostmanCollectionForApiEndpointRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    apiID: z.string(),
    versionID: z.string(),
    apiEndpointID: z.string(),
  });

/** @internal */
export type GeneratePostmanCollectionForApiEndpointRequest$Outbound = {
  apiID: string;
  versionID: string;
  apiEndpointID: string;
};

/** @internal */
export const GeneratePostmanCollectionForApiEndpointRequest$outboundSchema:
  z.ZodType<
    GeneratePostmanCollectionForApiEndpointRequest$Outbound,
    z.ZodTypeDef,
    GeneratePostmanCollectionForApiEndpointRequest
  > = z.object({
    apiID: z.string(),
    versionID: z.string(),
    apiEndpointID: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GeneratePostmanCollectionForApiEndpointRequest$ {
  /** @deprecated use `GeneratePostmanCollectionForApiEndpointRequest$inboundSchema` instead. */
  export const inboundSchema =
    GeneratePostmanCollectionForApiEndpointRequest$inboundSchema;
  /** @deprecated use `GeneratePostmanCollectionForApiEndpointRequest$outboundSchema` instead. */
  export const outboundSchema =
    GeneratePostmanCollectionForApiEndpointRequest$outboundSchema;
  /** @deprecated use `GeneratePostmanCollectionForApiEndpointRequest$Outbound` instead. */
  export type Outbound =
    GeneratePostmanCollectionForApiEndpointRequest$Outbound;
}

/** @internal */
export const GeneratePostmanCollectionForApiEndpointResponse$inboundSchema:
  z.ZodType<
    GeneratePostmanCollectionForApiEndpointResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    PostmanCollection: z.instanceof(ReadableStream<Uint8Array>).optional(),
  }).transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "PostmanCollection": "postmanCollection",
    });
  });

/** @internal */
export type GeneratePostmanCollectionForApiEndpointResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  PostmanCollection?: ReadableStream<Uint8Array> | undefined;
};

/** @internal */
export const GeneratePostmanCollectionForApiEndpointResponse$outboundSchema:
  z.ZodType<
    GeneratePostmanCollectionForApiEndpointResponse$Outbound,
    z.ZodTypeDef,
    GeneratePostmanCollectionForApiEndpointResponse
  > = z.object({
    httpMeta: components.HTTPMetadata$outboundSchema,
    postmanCollection: z.instanceof(ReadableStream<Uint8Array>).optional(),
  }).transform((v) => {
    return remap$(v, {
      httpMeta: "HttpMeta",
      postmanCollection: "PostmanCollection",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GeneratePostmanCollectionForApiEndpointResponse$ {
  /** @deprecated use `GeneratePostmanCollectionForApiEndpointResponse$inboundSchema` instead. */
  export const inboundSchema =
    GeneratePostmanCollectionForApiEndpointResponse$inboundSchema;
  /** @deprecated use `GeneratePostmanCollectionForApiEndpointResponse$outboundSchema` instead. */
  export const outboundSchema =
    GeneratePostmanCollectionForApiEndpointResponse$outboundSchema;
  /** @deprecated use `GeneratePostmanCollectionForApiEndpointResponse$Outbound` instead. */
  export type Outbound =
    GeneratePostmanCollectionForApiEndpointResponse$Outbound;
}
