/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type GenerateRequestPostmanCollectionRequest = {
    /**
     * The ID of the request to retrieve.
     */
    requestID: string;
};

export type GenerateRequestPostmanCollectionResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    postmanCollection?: ReadableStream<Uint8Array> | undefined;
    /**
     * Default error response
     */
    error?: errors.ErrorT | undefined;
};

/** @internal */
export namespace GenerateRequestPostmanCollectionRequest$ {
    export const inboundSchema: z.ZodType<
        GenerateRequestPostmanCollectionRequest,
        z.ZodTypeDef,
        unknown
    > = z.object({
        requestID: z.string(),
    });

    export type Outbound = {
        requestID: string;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GenerateRequestPostmanCollectionRequest
    > = z.object({
        requestID: z.string(),
    });
}

/** @internal */
export namespace GenerateRequestPostmanCollectionResponse$ {
    export const inboundSchema: z.ZodType<
        GenerateRequestPostmanCollectionResponse,
        z.ZodTypeDef,
        unknown
    > = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            PostmanCollection: z.instanceof(ReadableStream<Uint8Array>).optional(),
            Error: errors.ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                PostmanCollection: "postmanCollection",
                Error: "error",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        PostmanCollection?: ReadableStream<Uint8Array> | undefined;
        Error?: errors.ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GenerateRequestPostmanCollectionResponse
    > = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            postmanCollection: z.instanceof(ReadableStream<Uint8Array>).optional(),
            error: errors.ErrorT$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                postmanCollection: "PostmanCollection",
                error: "Error",
            });
        });
}
