/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type GeneratePostmanCollectionForApiEndpointRequest = {
    /**
     * The ID of the Api to generate a Postman collection for.
     */
    apiID: string;
    /**
     * The version ID of the Api to generate a Postman collection for.
     */
    versionID: string;
    /**
     * The ID of the ApiEndpoint to generate a Postman collection for.
     */
    apiEndpointID: string;
};

export type GeneratePostmanCollectionForApiEndpointResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    postmanCollection?: ReadableStream<Uint8Array> | undefined;
    /**
     * Default error response
     */
    error?: errors.ErrorT | undefined;
};

/** @internal */
export namespace GeneratePostmanCollectionForApiEndpointRequest$ {
    export const inboundSchema: z.ZodType<
        GeneratePostmanCollectionForApiEndpointRequest,
        z.ZodTypeDef,
        unknown
    > = z.object({
        apiID: z.string(),
        versionID: z.string(),
        apiEndpointID: z.string(),
    });

    export type Outbound = {
        apiID: string;
        versionID: string;
        apiEndpointID: string;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GeneratePostmanCollectionForApiEndpointRequest
    > = z.object({
        apiID: z.string(),
        versionID: z.string(),
        apiEndpointID: z.string(),
    });
}

/** @internal */
export namespace GeneratePostmanCollectionForApiEndpointResponse$ {
    export const inboundSchema: z.ZodType<
        GeneratePostmanCollectionForApiEndpointResponse,
        z.ZodTypeDef,
        unknown
    > = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            PostmanCollection: z.instanceof(ReadableStream<Uint8Array>).optional(),
            Error: errors.ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                PostmanCollection: "postmanCollection",
                Error: "error",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        PostmanCollection?: ReadableStream<Uint8Array> | undefined;
        Error?: errors.ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GeneratePostmanCollectionForApiEndpointResponse
    > = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            postmanCollection: z.instanceof(ReadableStream<Uint8Array>).optional(),
            error: errors.ErrorT$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                postmanCollection: "PostmanCollection",
                error: "Error",
            });
        });
}
