/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type GetActionRequest = {
    /**
     * The targetName of the workflow target.
     */
    targetName?: string | undefined;
    org: string;
    repo: string;
};

export type GetActionResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    githubGetActionResponse?: components.GithubGetActionResponse | undefined;
    /**
     * Default error response
     */
    error?: errors.ErrorT | undefined;
};

/** @internal */
export namespace GetActionRequest$ {
    export const inboundSchema: z.ZodType<GetActionRequest, z.ZodTypeDef, unknown> = z.object({
        targetName: z.string().optional(),
        org: z.string(),
        repo: z.string(),
    });

    export type Outbound = {
        targetName?: string | undefined;
        org: string;
        repo: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetActionRequest> = z.object({
        targetName: z.string().optional(),
        org: z.string(),
        repo: z.string(),
    });
}

/** @internal */
export namespace GetActionResponse$ {
    export const inboundSchema: z.ZodType<GetActionResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            GithubGetActionResponse: components.GithubGetActionResponse$.inboundSchema.optional(),
            Error: errors.ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                GithubGetActionResponse: "githubGetActionResponse",
                Error: "error",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        GithubGetActionResponse?: components.GithubGetActionResponse$.Outbound | undefined;
        Error?: errors.ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetActionResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            githubGetActionResponse: components.GithubGetActionResponse$.outboundSchema.optional(),
            error: errors.ErrorT$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                githubGetActionResponse: "GithubGetActionResponse",
                error: "Error",
            });
        });
}
