/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type GetAllForVersionApiEndpointsRequest = {
    /**
     * The ID of the Api to retrieve ApiEndpoints for.
     */
    apiID: string;
    /**
     * The version ID of the Api to retrieve ApiEndpoints for.
     */
    versionID: string;
};

export type GetAllForVersionApiEndpointsResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    apiEndpoints?: Array<components.ApiEndpoint> | undefined;
    /**
     * Default error response
     */
    error?: errors.ErrorT | undefined;
};

/** @internal */
export namespace GetAllForVersionApiEndpointsRequest$ {
    export const inboundSchema: z.ZodType<
        GetAllForVersionApiEndpointsRequest,
        z.ZodTypeDef,
        unknown
    > = z.object({
        apiID: z.string(),
        versionID: z.string(),
    });

    export type Outbound = {
        apiID: string;
        versionID: string;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetAllForVersionApiEndpointsRequest
    > = z.object({
        apiID: z.string(),
        versionID: z.string(),
    });
}

/** @internal */
export namespace GetAllForVersionApiEndpointsResponse$ {
    export const inboundSchema: z.ZodType<
        GetAllForVersionApiEndpointsResponse,
        z.ZodTypeDef,
        unknown
    > = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            APIEndpoints: z.array(components.ApiEndpoint$.inboundSchema).optional(),
            Error: errors.ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                APIEndpoints: "apiEndpoints",
                Error: "error",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        APIEndpoints?: Array<components.ApiEndpoint$.Outbound> | undefined;
        Error?: errors.ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetAllForVersionApiEndpointsResponse
    > = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            apiEndpoints: z.array(components.ApiEndpoint$.outboundSchema).optional(),
            error: errors.ErrorT$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                apiEndpoints: "APIEndpoints",
                error: "Error",
            });
        });
}
