/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetBillingAddOnsResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * Success
   */
  organizationBillingAddOnResponse?:
    | components.OrganizationBillingAddOnResponse
    | undefined;
};

/** @internal */
export const GetBillingAddOnsResponse$inboundSchema: z.ZodType<
  GetBillingAddOnsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  OrganizationBillingAddOnResponse: components
    .OrganizationBillingAddOnResponse$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "OrganizationBillingAddOnResponse": "organizationBillingAddOnResponse",
  });
});

/** @internal */
export type GetBillingAddOnsResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  OrganizationBillingAddOnResponse?:
    | components.OrganizationBillingAddOnResponse$Outbound
    | undefined;
};

/** @internal */
export const GetBillingAddOnsResponse$outboundSchema: z.ZodType<
  GetBillingAddOnsResponse$Outbound,
  z.ZodTypeDef,
  GetBillingAddOnsResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  organizationBillingAddOnResponse: components
    .OrganizationBillingAddOnResponse$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    organizationBillingAddOnResponse: "OrganizationBillingAddOnResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetBillingAddOnsResponse$ {
  /** @deprecated use `GetBillingAddOnsResponse$inboundSchema` instead. */
  export const inboundSchema = GetBillingAddOnsResponse$inboundSchema;
  /** @deprecated use `GetBillingAddOnsResponse$outboundSchema` instead. */
  export const outboundSchema = GetBillingAddOnsResponse$outboundSchema;
  /** @deprecated use `GetBillingAddOnsResponse$Outbound` instead. */
  export type Outbound = GetBillingAddOnsResponse$Outbound;
}

export function getBillingAddOnsResponseToJSON(
  getBillingAddOnsResponse: GetBillingAddOnsResponse,
): string {
  return JSON.stringify(
    GetBillingAddOnsResponse$outboundSchema.parse(getBillingAddOnsResponse),
  );
}

export function getBillingAddOnsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetBillingAddOnsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBillingAddOnsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBillingAddOnsResponse' from JSON`,
  );
}
