/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetBlobRequest = {
  organizationSlug: string;
  workspaceSlug: string;
  namespaceName: string;
  digest: string;
};

export type GetBlobResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  blob?: ReadableStream<Uint8Array> | undefined;
};

/** @internal */
export type GetBlobRequest$Outbound = {
  organization_slug: string;
  workspace_slug: string;
  namespace_name: string;
  digest: string;
};

/** @internal */
export const GetBlobRequest$outboundSchema: z.ZodType<
  GetBlobRequest$Outbound,
  z.ZodTypeDef,
  GetBlobRequest
> = z.object({
  organizationSlug: z.string(),
  workspaceSlug: z.string(),
  namespaceName: z.string(),
  digest: z.string(),
}).transform((v) => {
  return remap$(v, {
    organizationSlug: "organization_slug",
    workspaceSlug: "workspace_slug",
    namespaceName: "namespace_name",
  });
});

export function getBlobRequestToJSON(getBlobRequest: GetBlobRequest): string {
  return JSON.stringify(GetBlobRequest$outboundSchema.parse(getBlobRequest));
}

/** @internal */
export const GetBlobResponse$inboundSchema: z.ZodType<
  GetBlobResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  Blob: z.instanceof(ReadableStream<Uint8Array>).optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "Blob": "blob",
  });
});

export function getBlobResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetBlobResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBlobResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBlobResponse' from JSON`,
  );
}
