/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MethodPaths = {
  method: components.HttpMethod;
  path: string;
};

export type GetCodeSamplesRequest = {
  /**
   * The registry URL from which to retrieve the snippets.
   */
  registryUrl: string;
  /**
   * The operation IDs to retrieve snippets for.
   */
  operationIds?: Array<string> | undefined;
  /**
   * The method paths to retrieve snippets for.
   */
  methodPaths?: Array<MethodPaths> | undefined;
  /**
   * The languages to retrieve snippets for.
   */
  languages?: Array<string> | undefined;
};

export type GetCodeSamplesResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  usageSnippets?: components.UsageSnippets | undefined;
};

/** @internal */
export type MethodPaths$Outbound = {
  method: string;
  path: string;
};

/** @internal */
export const MethodPaths$outboundSchema: z.ZodType<
  MethodPaths$Outbound,
  z.ZodTypeDef,
  MethodPaths
> = z.object({
  method: components.HttpMethod$outboundSchema,
  path: z.string(),
});

export function methodPathsToJSON(methodPaths: MethodPaths): string {
  return JSON.stringify(MethodPaths$outboundSchema.parse(methodPaths));
}

/** @internal */
export type GetCodeSamplesRequest$Outbound = {
  registry_url: string;
  operation_ids?: Array<string> | undefined;
  method_paths?: Array<MethodPaths$Outbound> | undefined;
  languages?: Array<string> | undefined;
};

/** @internal */
export const GetCodeSamplesRequest$outboundSchema: z.ZodType<
  GetCodeSamplesRequest$Outbound,
  z.ZodTypeDef,
  GetCodeSamplesRequest
> = z.object({
  registryUrl: z.string(),
  operationIds: z.array(z.string()).optional(),
  methodPaths: z.array(z.lazy(() => MethodPaths$outboundSchema)).optional(),
  languages: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    registryUrl: "registry_url",
    operationIds: "operation_ids",
    methodPaths: "method_paths",
  });
});

export function getCodeSamplesRequestToJSON(
  getCodeSamplesRequest: GetCodeSamplesRequest,
): string {
  return JSON.stringify(
    GetCodeSamplesRequest$outboundSchema.parse(getCodeSamplesRequest),
  );
}

/** @internal */
export const GetCodeSamplesResponse$inboundSchema: z.ZodType<
  GetCodeSamplesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  UsageSnippets: components.UsageSnippets$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "UsageSnippets": "usageSnippets",
  });
});

export function getCodeSamplesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCodeSamplesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCodeSamplesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCodeSamplesResponse' from JSON`,
  );
}
