/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as errors from "../errors/index.js";

export type GetNamespacesResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  getNamespacesResponse?: components.GetNamespacesResponse | undefined;
  /**
   * Default error response
   */
  error?: errors.ErrorT | undefined;
};

/** @internal */
export const GetNamespacesResponse$inboundSchema: z.ZodType<
  GetNamespacesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  GetNamespacesResponse: components.GetNamespacesResponse$inboundSchema
    .optional(),
  Error: errors.ErrorT$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "GetNamespacesResponse": "getNamespacesResponse",
    "Error": "error",
  });
});

/** @internal */
export type GetNamespacesResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  GetNamespacesResponse?: components.GetNamespacesResponse$Outbound | undefined;
  Error?: errors.ErrorT$Outbound | undefined;
};

/** @internal */
export const GetNamespacesResponse$outboundSchema: z.ZodType<
  GetNamespacesResponse$Outbound,
  z.ZodTypeDef,
  GetNamespacesResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  getNamespacesResponse: components.GetNamespacesResponse$outboundSchema
    .optional(),
  error: errors.ErrorT$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    getNamespacesResponse: "GetNamespacesResponse",
    error: "Error",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetNamespacesResponse$ {
  /** @deprecated use `GetNamespacesResponse$inboundSchema` instead. */
  export const inboundSchema = GetNamespacesResponse$inboundSchema;
  /** @deprecated use `GetNamespacesResponse$outboundSchema` instead. */
  export const outboundSchema = GetNamespacesResponse$outboundSchema;
  /** @deprecated use `GetNamespacesResponse$Outbound` instead. */
  export type Outbound = GetNamespacesResponse$Outbound;
}
