/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetNamespacesResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  getNamespacesResponse?: components.GetNamespacesResponse | undefined;
};

/** @internal */
export const GetNamespacesResponse$inboundSchema: z.ZodType<
  GetNamespacesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  GetNamespacesResponse: components.GetNamespacesResponse$inboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "GetNamespacesResponse": "getNamespacesResponse",
  });
});

export function getNamespacesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetNamespacesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetNamespacesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetNamespacesResponse' from JSON`,
  );
}
