/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type GetOrganizationsResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    organizations?: Array<components.Organization> | undefined;
    /**
     * Default error response
     */
    error?: errors.ErrorT | undefined;
};

/** @internal */
export namespace GetOrganizationsResponse$ {
    export const inboundSchema: z.ZodType<GetOrganizationsResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            Organizations: z.array(components.Organization$.inboundSchema).optional(),
            Error: errors.ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                Organizations: "organizations",
                Error: "error",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Organizations?: Array<components.Organization$.Outbound> | undefined;
        Error?: errors.ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetOrganizationsResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            organizations: z.array(components.Organization$.outboundSchema).optional(),
            error: errors.ErrorT$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                organizations: "Organizations",
                error: "Error",
            });
        });
}
