/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type GetRevisionsRequest = {
    namespaceName: string;
    /**
     * Token to retrieve the next page of results
     */
    nextPageToken?: string | undefined;
};

export type GetRevisionsResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    getRevisionsResponse?: components.GetRevisionsResponse | undefined;
    /**
     * Default error response
     */
    error?: errors.ErrorT | undefined;
};

/** @internal */
export namespace GetRevisionsRequest$ {
    export const inboundSchema: z.ZodType<GetRevisionsRequest, z.ZodTypeDef, unknown> = z
        .object({
            namespace_name: z.string(),
            next_page_token: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                namespace_name: "namespaceName",
                next_page_token: "nextPageToken",
            });
        });

    export type Outbound = {
        namespace_name: string;
        next_page_token?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetRevisionsRequest> = z
        .object({
            namespaceName: z.string(),
            nextPageToken: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                namespaceName: "namespace_name",
                nextPageToken: "next_page_token",
            });
        });
}

/** @internal */
export namespace GetRevisionsResponse$ {
    export const inboundSchema: z.ZodType<GetRevisionsResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            GetRevisionsResponse: components.GetRevisionsResponse$.inboundSchema.optional(),
            Error: errors.ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                GetRevisionsResponse: "getRevisionsResponse",
                Error: "error",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        GetRevisionsResponse?: components.GetRevisionsResponse$.Outbound | undefined;
        Error?: errors.ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetRevisionsResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            getRevisionsResponse: components.GetRevisionsResponse$.outboundSchema.optional(),
            error: errors.ErrorT$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                getRevisionsResponse: "GetRevisionsResponse",
                error: "Error",
            });
        });
}
