/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type GetSchemaRequest = {
    /**
     * The ID of the Api to get the schema for.
     */
    apiID: string;
    /**
     * The version ID of the Api to delete metadata for.
     */
    versionID: string;
};

export type GetSchemaResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    schema?: components.Schema | undefined;
    /**
     * Default error response
     */
    error?: errors.ErrorT | undefined;
};

/** @internal */
export namespace GetSchemaRequest$ {
    export const inboundSchema: z.ZodType<GetSchemaRequest, z.ZodTypeDef, unknown> = z.object({
        apiID: z.string(),
        versionID: z.string(),
    });

    export type Outbound = {
        apiID: string;
        versionID: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetSchemaRequest> = z.object({
        apiID: z.string(),
        versionID: z.string(),
    });
}

/** @internal */
export namespace GetSchemaResponse$ {
    export const inboundSchema: z.ZodType<GetSchemaResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            Schema: components.Schema$.inboundSchema.optional(),
            Error: errors.ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                Schema: "schema",
                Error: "error",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Schema?: components.Schema$.Outbound | undefined;
        Error?: errors.ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetSchemaResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            schema: components.Schema$.outboundSchema.optional(),
            error: errors.ErrorT$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                schema: "Schema",
                error: "Error",
            });
        });
}
