/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type GetTagsRequest = {
    namespaceName: string;
};

export type GetTagsResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    getTagsResponse?: components.GetTagsResponse | undefined;
    /**
     * Default error response
     */
    error?: errors.ErrorT | undefined;
};

/** @internal */
export namespace GetTagsRequest$ {
    export const inboundSchema: z.ZodType<GetTagsRequest, z.ZodTypeDef, unknown> = z
        .object({
            namespace_name: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                namespace_name: "namespaceName",
            });
        });

    export type Outbound = {
        namespace_name: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetTagsRequest> = z
        .object({
            namespaceName: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                namespaceName: "namespace_name",
            });
        });
}

/** @internal */
export namespace GetTagsResponse$ {
    export const inboundSchema: z.ZodType<GetTagsResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            GetTagsResponse: components.GetTagsResponse$.inboundSchema.optional(),
            Error: errors.ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                GetTagsResponse: "getTagsResponse",
                Error: "error",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        GetTagsResponse?: components.GetTagsResponse$.Outbound | undefined;
        Error?: errors.ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetTagsResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            getTagsResponse: components.GetTagsResponse$.outboundSchema.optional(),
            error: errors.ErrorT$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                getTagsResponse: "GetTagsResponse",
                error: "Error",
            });
        });
}
