/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type GetValidEmbedAccessTokensResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  embedTokens?: Array<components.EmbedToken> | undefined;
};

/** @internal */
export const GetValidEmbedAccessTokensResponse$inboundSchema: z.ZodType<
  GetValidEmbedAccessTokensResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  EmbedTokens: z.array(components.EmbedToken$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "EmbedTokens": "embedTokens",
  });
});

/** @internal */
export type GetValidEmbedAccessTokensResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  EmbedTokens?: Array<components.EmbedToken$Outbound> | undefined;
};

/** @internal */
export const GetValidEmbedAccessTokensResponse$outboundSchema: z.ZodType<
  GetValidEmbedAccessTokensResponse$Outbound,
  z.ZodTypeDef,
  GetValidEmbedAccessTokensResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  embedTokens: z.array(components.EmbedToken$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    embedTokens: "EmbedTokens",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetValidEmbedAccessTokensResponse$ {
  /** @deprecated use `GetValidEmbedAccessTokensResponse$inboundSchema` instead. */
  export const inboundSchema = GetValidEmbedAccessTokensResponse$inboundSchema;
  /** @deprecated use `GetValidEmbedAccessTokensResponse$outboundSchema` instead. */
  export const outboundSchema =
    GetValidEmbedAccessTokensResponse$outboundSchema;
  /** @deprecated use `GetValidEmbedAccessTokensResponse$Outbound` instead. */
  export type Outbound = GetValidEmbedAccessTokensResponse$Outbound;
}
