/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetWorkspaceSettingsGlobals = {
  workspaceId?: string | undefined;
};

export type GetWorkspaceSettingsRequest = {
  /**
   * Unique identifier of the workspace.
   */
  workspaceId?: string | undefined;
};

export type GetWorkspaceSettingsResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  workspaceSettings?: components.WorkspaceSettings | undefined;
};

/** @internal */
export type GetWorkspaceSettingsRequest$Outbound = {
  workspace_id?: string | undefined;
};

/** @internal */
export const GetWorkspaceSettingsRequest$outboundSchema: z.ZodType<
  GetWorkspaceSettingsRequest$Outbound,
  z.ZodTypeDef,
  GetWorkspaceSettingsRequest
> = z.object({
  workspaceId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    workspaceId: "workspace_id",
  });
});

export function getWorkspaceSettingsRequestToJSON(
  getWorkspaceSettingsRequest: GetWorkspaceSettingsRequest,
): string {
  return JSON.stringify(
    GetWorkspaceSettingsRequest$outboundSchema.parse(
      getWorkspaceSettingsRequest,
    ),
  );
}

/** @internal */
export const GetWorkspaceSettingsResponse$inboundSchema: z.ZodType<
  GetWorkspaceSettingsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  WorkspaceSettings: components.WorkspaceSettings$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "WorkspaceSettings": "workspaceSettings",
  });
});

export function getWorkspaceSettingsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetWorkspaceSettingsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWorkspaceSettingsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWorkspaceSettingsResponse' from JSON`,
  );
}
