/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetWorkspaceGlobals = {
  workspaceId?: string | undefined;
};

export type GetWorkspaceRequest = {
  /**
   * Unique identifier of the workspace.
   */
  workspaceId?: string | undefined;
};

export type GetWorkspaceResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  workspace?: components.Workspace | undefined;
};

/** @internal */
export type GetWorkspaceRequest$Outbound = {
  workspace_id?: string | undefined;
};

/** @internal */
export const GetWorkspaceRequest$outboundSchema: z.ZodType<
  GetWorkspaceRequest$Outbound,
  z.ZodTypeDef,
  GetWorkspaceRequest
> = z.object({
  workspaceId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    workspaceId: "workspace_id",
  });
});

export function getWorkspaceRequestToJSON(
  getWorkspaceRequest: GetWorkspaceRequest,
): string {
  return JSON.stringify(
    GetWorkspaceRequest$outboundSchema.parse(getWorkspaceRequest),
  );
}

/** @internal */
export const GetWorkspaceResponse$inboundSchema: z.ZodType<
  GetWorkspaceResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  Workspace: components.Workspace$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "Workspace": "workspace",
  });
});

export function getWorkspaceResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetWorkspaceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWorkspaceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWorkspaceResponse' from JSON`,
  );
}
