/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GithubConfigureCodeSamplesResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  githubConfigureCodeSamplesResponse?:
    | components.GithubConfigureCodeSamplesResponse
    | undefined;
};

/** @internal */
export const GithubConfigureCodeSamplesResponse$inboundSchema: z.ZodType<
  GithubConfigureCodeSamplesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  GithubConfigureCodeSamplesResponse: components
    .GithubConfigureCodeSamplesResponse$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "GithubConfigureCodeSamplesResponse": "githubConfigureCodeSamplesResponse",
  });
});

export function githubConfigureCodeSamplesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GithubConfigureCodeSamplesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GithubConfigureCodeSamplesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GithubConfigureCodeSamplesResponse' from JSON`,
  );
}
