/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GithubConfigureTargetResponse = {
  httpMeta: components.HTTPMetadata;
};

/** @internal */
export const GithubConfigureTargetResponse$inboundSchema: z.ZodType<
  GithubConfigureTargetResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
  });
});

/** @internal */
export type GithubConfigureTargetResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
};

/** @internal */
export const GithubConfigureTargetResponse$outboundSchema: z.ZodType<
  GithubConfigureTargetResponse$Outbound,
  z.ZodTypeDef,
  GithubConfigureTargetResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GithubConfigureTargetResponse$ {
  /** @deprecated use `GithubConfigureTargetResponse$inboundSchema` instead. */
  export const inboundSchema = GithubConfigureTargetResponse$inboundSchema;
  /** @deprecated use `GithubConfigureTargetResponse$outboundSchema` instead. */
  export const outboundSchema = GithubConfigureTargetResponse$outboundSchema;
  /** @deprecated use `GithubConfigureTargetResponse$Outbound` instead. */
  export type Outbound = GithubConfigureTargetResponse$Outbound;
}

export function githubConfigureTargetResponseToJSON(
  githubConfigureTargetResponse: GithubConfigureTargetResponse,
): string {
  return JSON.stringify(
    GithubConfigureTargetResponse$outboundSchema.parse(
      githubConfigureTargetResponse,
    ),
  );
}

export function githubConfigureTargetResponseFromJSON(
  jsonString: string,
): SafeParseResult<GithubConfigureTargetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GithubConfigureTargetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GithubConfigureTargetResponse' from JSON`,
  );
}
