/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type InsertVersionMetadataRequest = {
    /**
     * The ID of the Api to insert metadata for.
     */
    apiID: string;
    /**
     * The version ID of the Api to insert metadata for.
     */
    versionID: string;
    /**
     * A JSON representation of the metadata to insert.
     */
    versionMetadata: components.VersionMetadataInput;
};

export type InsertVersionMetadataResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    versionMetadata?: components.VersionMetadata | undefined;
    /**
     * Default error response
     */
    error?: errors.ErrorT | undefined;
};

/** @internal */
export namespace InsertVersionMetadataRequest$ {
    export const inboundSchema: z.ZodType<InsertVersionMetadataRequest, z.ZodTypeDef, unknown> = z
        .object({
            apiID: z.string(),
            versionID: z.string(),
            VersionMetadata: components.VersionMetadataInput$.inboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                VersionMetadata: "versionMetadata",
            });
        });

    export type Outbound = {
        apiID: string;
        versionID: string;
        VersionMetadata: components.VersionMetadataInput$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, InsertVersionMetadataRequest> = z
        .object({
            apiID: z.string(),
            versionID: z.string(),
            versionMetadata: components.VersionMetadataInput$.outboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                versionMetadata: "VersionMetadata",
            });
        });
}

/** @internal */
export namespace InsertVersionMetadataResponse$ {
    export const inboundSchema: z.ZodType<InsertVersionMetadataResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            VersionMetadata: components.VersionMetadata$.inboundSchema.optional(),
            Error: errors.ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                VersionMetadata: "versionMetadata",
                Error: "error",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        VersionMetadata?: components.VersionMetadata$.Outbound | undefined;
        Error?: errors.ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, InsertVersionMetadataResponse> =
        z
            .object({
                httpMeta: components.HTTPMetadata$.outboundSchema,
                versionMetadata: components.VersionMetadata$.outboundSchema.optional(),
                error: errors.ErrorT$.outboundSchema.optional(),
            })
            .transform((v) => {
                return remap$(v, {
                    httpMeta: "HttpMeta",
                    versionMetadata: "VersionMetadata",
                    error: "Error",
                });
            });
}
