/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListRemoteSourcesRequest = {
  namespaceName: string;
};

export type ListRemoteSourcesResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  remoteSource?: components.RemoteSource | undefined;
};

/** @internal */
export type ListRemoteSourcesRequest$Outbound = {
  namespace_name: string;
};

/** @internal */
export const ListRemoteSourcesRequest$outboundSchema: z.ZodType<
  ListRemoteSourcesRequest$Outbound,
  z.ZodTypeDef,
  ListRemoteSourcesRequest
> = z.object({
  namespaceName: z.string(),
}).transform((v) => {
  return remap$(v, {
    namespaceName: "namespace_name",
  });
});

export function listRemoteSourcesRequestToJSON(
  listRemoteSourcesRequest: ListRemoteSourcesRequest,
): string {
  return JSON.stringify(
    ListRemoteSourcesRequest$outboundSchema.parse(listRemoteSourcesRequest),
  );
}

/** @internal */
export const ListRemoteSourcesResponse$inboundSchema: z.ZodType<
  ListRemoteSourcesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  RemoteSource: components.RemoteSource$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "RemoteSource": "remoteSource",
  });
});

export function listRemoteSourcesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListRemoteSourcesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListRemoteSourcesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListRemoteSourcesResponse' from JSON`,
  );
}
