/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type PreflightResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    preflightToken?: components.PreflightToken | undefined;
    /**
     * Default error response
     */
    error?: errors.ErrorT | undefined;
};

/** @internal */
export namespace PreflightResponse$ {
    export const inboundSchema: z.ZodType<PreflightResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            PreflightToken: components.PreflightToken$.inboundSchema.optional(),
            Error: errors.ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                PreflightToken: "preflightToken",
                Error: "error",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        PreflightToken?: components.PreflightToken$.Outbound | undefined;
        Error?: errors.ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PreflightResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            preflightToken: components.PreflightToken$.outboundSchema.optional(),
            error: errors.ErrorT$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                preflightToken: "PreflightToken",
                error: "Error",
            });
        });
}
