/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as b64$ from "../../lib/base64.js";
import { remap as remap$ } from "../../lib/primitives.js";
import { blobLikeSchema } from "../../types/blobs.js";
import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type FileT = {
    fileName: string;
    content: Uint8Array | string;
};

/**
 * The schema file to upload provided as a multipart/form-data file segment.
 */
export type RegisterSchemaRequestBody = {
    file: FileT | Blob;
};

export type RegisterSchemaRequest = {
    /**
     * The ID of the Api to get the schema for.
     */
    apiID: string;
    /**
     * The version ID of the Api to delete metadata for.
     */
    versionID: string;
    /**
     * The schema file to upload provided as a multipart/form-data file segment.
     */
    requestBody: RegisterSchemaRequestBody;
};

export type RegisterSchemaResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Default error response
     */
    error?: errors.ErrorT | undefined;
};

/** @internal */
export namespace FileT$ {
    export const inboundSchema: z.ZodType<FileT, z.ZodTypeDef, unknown> = z.object({
        fileName: z.string(),
        content: b64$.zodInbound,
    });

    export type Outbound = {
        fileName: string;
        content: Uint8Array;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, FileT> = z.object({
        fileName: z.string(),
        content: b64$.zodOutbound,
    });
}

/** @internal */
export namespace RegisterSchemaRequestBody$ {
    export const inboundSchema: z.ZodType<RegisterSchemaRequestBody, z.ZodTypeDef, unknown> =
        z.object({
            file: z.lazy(() => FileT$.inboundSchema),
        });

    export type Outbound = {
        file: FileT$.Outbound | Blob;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RegisterSchemaRequestBody> =
        z.object({
            file: z.lazy(() => FileT$.outboundSchema).or(blobLikeSchema),
        });
}

/** @internal */
export namespace RegisterSchemaRequest$ {
    export const inboundSchema: z.ZodType<RegisterSchemaRequest, z.ZodTypeDef, unknown> = z
        .object({
            apiID: z.string(),
            versionID: z.string(),
            RequestBody: z.lazy(() => RegisterSchemaRequestBody$.inboundSchema),
        })
        .transform((v) => {
            return remap$(v, {
                RequestBody: "requestBody",
            });
        });

    export type Outbound = {
        apiID: string;
        versionID: string;
        RequestBody: RegisterSchemaRequestBody$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RegisterSchemaRequest> = z
        .object({
            apiID: z.string(),
            versionID: z.string(),
            requestBody: z.lazy(() => RegisterSchemaRequestBody$.outboundSchema),
        })
        .transform((v) => {
            return remap$(v, {
                requestBody: "RequestBody",
            });
        });
}

/** @internal */
export namespace RegisterSchemaResponse$ {
    export const inboundSchema: z.ZodType<RegisterSchemaResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            Error: errors.ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                Error: "error",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Error?: errors.ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RegisterSchemaResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            error: errors.ErrorT$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                error: "Error",
            });
        });
}
