/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type SuggestOperationIDsRegistryRequest = {
    xSessionId: string;
    namespaceName: string;
    /**
     * Tag or digest
     */
    revisionReference: string;
    /**
     * Max number of suggestions to request
     */
    limit?: number | undefined;
    /**
     * The schema file to upload provided as a multipart/form-data file segment.
     */
    suggestOperationIDsOpts?: components.SuggestOperationIDsOpts | undefined;
};

export type SuggestOperationIDsRegistryResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    suggestedOperationIDs?: components.SuggestedOperationIDs | undefined;
};

/** @internal */
export const SuggestOperationIDsRegistryRequest$inboundSchema: z.ZodType<
    SuggestOperationIDsRegistryRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        "x-session-id": z.string(),
        namespace_name: z.string(),
        revision_reference: z.string(),
        limit: z.number().optional(),
        SuggestOperationIDsOpts: components.SuggestOperationIDsOpts$inboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            "x-session-id": "xSessionId",
            namespace_name: "namespaceName",
            revision_reference: "revisionReference",
            SuggestOperationIDsOpts: "suggestOperationIDsOpts",
        });
    });

/** @internal */
export type SuggestOperationIDsRegistryRequest$Outbound = {
    "x-session-id": string;
    namespace_name: string;
    revision_reference: string;
    limit?: number | undefined;
    SuggestOperationIDsOpts?: components.SuggestOperationIDsOpts$Outbound | undefined;
};

/** @internal */
export const SuggestOperationIDsRegistryRequest$outboundSchema: z.ZodType<
    SuggestOperationIDsRegistryRequest$Outbound,
    z.ZodTypeDef,
    SuggestOperationIDsRegistryRequest
> = z
    .object({
        xSessionId: z.string(),
        namespaceName: z.string(),
        revisionReference: z.string(),
        limit: z.number().optional(),
        suggestOperationIDsOpts: components.SuggestOperationIDsOpts$outboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            xSessionId: "x-session-id",
            namespaceName: "namespace_name",
            revisionReference: "revision_reference",
            suggestOperationIDsOpts: "SuggestOperationIDsOpts",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SuggestOperationIDsRegistryRequest$ {
    /** @deprecated use `SuggestOperationIDsRegistryRequest$inboundSchema` instead. */
    export const inboundSchema = SuggestOperationIDsRegistryRequest$inboundSchema;
    /** @deprecated use `SuggestOperationIDsRegistryRequest$outboundSchema` instead. */
    export const outboundSchema = SuggestOperationIDsRegistryRequest$outboundSchema;
    /** @deprecated use `SuggestOperationIDsRegistryRequest$Outbound` instead. */
    export type Outbound = SuggestOperationIDsRegistryRequest$Outbound;
}

/** @internal */
export const SuggestOperationIDsRegistryResponse$inboundSchema: z.ZodType<
    SuggestOperationIDsRegistryResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        HttpMeta: components.HTTPMetadata$inboundSchema,
        SuggestedOperationIDs: components.SuggestedOperationIDs$inboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            HttpMeta: "httpMeta",
            SuggestedOperationIDs: "suggestedOperationIDs",
        });
    });

/** @internal */
export type SuggestOperationIDsRegistryResponse$Outbound = {
    HttpMeta: components.HTTPMetadata$Outbound;
    SuggestedOperationIDs?: components.SuggestedOperationIDs$Outbound | undefined;
};

/** @internal */
export const SuggestOperationIDsRegistryResponse$outboundSchema: z.ZodType<
    SuggestOperationIDsRegistryResponse$Outbound,
    z.ZodTypeDef,
    SuggestOperationIDsRegistryResponse
> = z
    .object({
        httpMeta: components.HTTPMetadata$outboundSchema,
        suggestedOperationIDs: components.SuggestedOperationIDs$outboundSchema.optional(),
    })
    .transform((v) => {
        return remap$(v, {
            httpMeta: "HttpMeta",
            suggestedOperationIDs: "SuggestedOperationIDs",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SuggestOperationIDsRegistryResponse$ {
    /** @deprecated use `SuggestOperationIDsRegistryResponse$inboundSchema` instead. */
    export const inboundSchema = SuggestOperationIDsRegistryResponse$inboundSchema;
    /** @deprecated use `SuggestOperationIDsRegistryResponse$outboundSchema` instead. */
    export const outboundSchema = SuggestOperationIDsRegistryResponse$outboundSchema;
    /** @deprecated use `SuggestOperationIDsRegistryResponse$Outbound` instead. */
    export type Outbound = SuggestOperationIDsRegistryResponse$Outbound;
}
