/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SuggestItemsResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * One suggestion per item. Guaranteed to be the same length as the input items.
   */
  strings?: Array<string> | undefined;
};

/** @internal */
export const SuggestItemsResponse$inboundSchema: z.ZodType<
  SuggestItemsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  strings: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
  });
});

export function suggestItemsResponseFromJSON(
  jsonString: string,
): SafeParseResult<SuggestItemsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SuggestItemsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SuggestItemsResponse' from JSON`,
  );
}
