/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The publishing token to update
 */
export type UpdatePublishingTokenExpirationRequestBody = {
  /**
   * The new expiration date for the publishing token.
   */
  validUntil: Date;
  /**
   * The new name for the publishing token.
   */
  tokenName?: string | undefined;
};

export type UpdatePublishingTokenExpirationRequest = {
  /**
   * Unique identifier of the publishing token.
   */
  tokenID: string;
  /**
   * The publishing token to update
   */
  requestBody?: UpdatePublishingTokenExpirationRequestBody | undefined;
};

export type UpdatePublishingTokenExpirationResponse = {
  httpMeta: components.HTTPMetadata;
};

/** @internal */
export const UpdatePublishingTokenExpirationRequestBody$inboundSchema:
  z.ZodType<UpdatePublishingTokenExpirationRequestBody, z.ZodTypeDef, unknown> =
    z.object({
      valid_until: z.string().datetime({ offset: true }).transform(v =>
        new Date(v)
      ),
      token_name: z.string().optional(),
    }).transform((v) => {
      return remap$(v, {
        "valid_until": "validUntil",
        "token_name": "tokenName",
      });
    });

/** @internal */
export type UpdatePublishingTokenExpirationRequestBody$Outbound = {
  valid_until: string;
  token_name?: string | undefined;
};

/** @internal */
export const UpdatePublishingTokenExpirationRequestBody$outboundSchema:
  z.ZodType<
    UpdatePublishingTokenExpirationRequestBody$Outbound,
    z.ZodTypeDef,
    UpdatePublishingTokenExpirationRequestBody
  > = z.object({
    validUntil: z.date().transform(v => v.toISOString()),
    tokenName: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      validUntil: "valid_until",
      tokenName: "token_name",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdatePublishingTokenExpirationRequestBody$ {
  /** @deprecated use `UpdatePublishingTokenExpirationRequestBody$inboundSchema` instead. */
  export const inboundSchema =
    UpdatePublishingTokenExpirationRequestBody$inboundSchema;
  /** @deprecated use `UpdatePublishingTokenExpirationRequestBody$outboundSchema` instead. */
  export const outboundSchema =
    UpdatePublishingTokenExpirationRequestBody$outboundSchema;
  /** @deprecated use `UpdatePublishingTokenExpirationRequestBody$Outbound` instead. */
  export type Outbound = UpdatePublishingTokenExpirationRequestBody$Outbound;
}

export function updatePublishingTokenExpirationRequestBodyToJSON(
  updatePublishingTokenExpirationRequestBody:
    UpdatePublishingTokenExpirationRequestBody,
): string {
  return JSON.stringify(
    UpdatePublishingTokenExpirationRequestBody$outboundSchema.parse(
      updatePublishingTokenExpirationRequestBody,
    ),
  );
}

export function updatePublishingTokenExpirationRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdatePublishingTokenExpirationRequestBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdatePublishingTokenExpirationRequestBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdatePublishingTokenExpirationRequestBody' from JSON`,
  );
}

/** @internal */
export const UpdatePublishingTokenExpirationRequest$inboundSchema: z.ZodType<
  UpdatePublishingTokenExpirationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  tokenID: z.string(),
  RequestBody: z.lazy(() =>
    UpdatePublishingTokenExpirationRequestBody$inboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type UpdatePublishingTokenExpirationRequest$Outbound = {
  tokenID: string;
  RequestBody?: UpdatePublishingTokenExpirationRequestBody$Outbound | undefined;
};

/** @internal */
export const UpdatePublishingTokenExpirationRequest$outboundSchema: z.ZodType<
  UpdatePublishingTokenExpirationRequest$Outbound,
  z.ZodTypeDef,
  UpdatePublishingTokenExpirationRequest
> = z.object({
  tokenID: z.string(),
  requestBody: z.lazy(() =>
    UpdatePublishingTokenExpirationRequestBody$outboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdatePublishingTokenExpirationRequest$ {
  /** @deprecated use `UpdatePublishingTokenExpirationRequest$inboundSchema` instead. */
  export const inboundSchema =
    UpdatePublishingTokenExpirationRequest$inboundSchema;
  /** @deprecated use `UpdatePublishingTokenExpirationRequest$outboundSchema` instead. */
  export const outboundSchema =
    UpdatePublishingTokenExpirationRequest$outboundSchema;
  /** @deprecated use `UpdatePublishingTokenExpirationRequest$Outbound` instead. */
  export type Outbound = UpdatePublishingTokenExpirationRequest$Outbound;
}

export function updatePublishingTokenExpirationRequestToJSON(
  updatePublishingTokenExpirationRequest:
    UpdatePublishingTokenExpirationRequest,
): string {
  return JSON.stringify(
    UpdatePublishingTokenExpirationRequest$outboundSchema.parse(
      updatePublishingTokenExpirationRequest,
    ),
  );
}

export function updatePublishingTokenExpirationRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdatePublishingTokenExpirationRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UpdatePublishingTokenExpirationRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePublishingTokenExpirationRequest' from JSON`,
  );
}

/** @internal */
export const UpdatePublishingTokenExpirationResponse$inboundSchema: z.ZodType<
  UpdatePublishingTokenExpirationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
  });
});

/** @internal */
export type UpdatePublishingTokenExpirationResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
};

/** @internal */
export const UpdatePublishingTokenExpirationResponse$outboundSchema: z.ZodType<
  UpdatePublishingTokenExpirationResponse$Outbound,
  z.ZodTypeDef,
  UpdatePublishingTokenExpirationResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdatePublishingTokenExpirationResponse$ {
  /** @deprecated use `UpdatePublishingTokenExpirationResponse$inboundSchema` instead. */
  export const inboundSchema =
    UpdatePublishingTokenExpirationResponse$inboundSchema;
  /** @deprecated use `UpdatePublishingTokenExpirationResponse$outboundSchema` instead. */
  export const outboundSchema =
    UpdatePublishingTokenExpirationResponse$outboundSchema;
  /** @deprecated use `UpdatePublishingTokenExpirationResponse$Outbound` instead. */
  export type Outbound = UpdatePublishingTokenExpirationResponse$Outbound;
}

export function updatePublishingTokenExpirationResponseToJSON(
  updatePublishingTokenExpirationResponse:
    UpdatePublishingTokenExpirationResponse,
): string {
  return JSON.stringify(
    UpdatePublishingTokenExpirationResponse$outboundSchema.parse(
      updatePublishingTokenExpirationResponse,
    ),
  );
}

export function updatePublishingTokenExpirationResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdatePublishingTokenExpirationResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdatePublishingTokenExpirationResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdatePublishingTokenExpirationResponse' from JSON`,
  );
}
