/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as errors from "../errors/index.js";
import * as z from "zod";

export type UpsertApiRequest = {
    /**
     * The ID of the Api to upsert.
     */
    apiID: string;
    /**
     * A JSON representation of the Api to upsert
     */
    api: components.ApiInput;
};

export type UpsertApiResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    api?: components.Api | undefined;
    /**
     * Default error response
     */
    error?: errors.ErrorT | undefined;
};

/** @internal */
export namespace UpsertApiRequest$ {
    export const inboundSchema: z.ZodType<UpsertApiRequest, z.ZodTypeDef, unknown> = z
        .object({
            apiID: z.string(),
            Api: components.ApiInput$.inboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                Api: "api",
            });
        });

    export type Outbound = {
        apiID: string;
        Api: components.ApiInput$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpsertApiRequest> = z
        .object({
            apiID: z.string(),
            api: components.ApiInput$.outboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                api: "Api",
            });
        });
}

/** @internal */
export namespace UpsertApiResponse$ {
    export const inboundSchema: z.ZodType<UpsertApiResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            Api: components.Api$.inboundSchema.optional(),
            Error: errors.ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                Api: "api",
                Error: "error",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Api?: components.Api$.Outbound | undefined;
        Error?: errors.ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpsertApiResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            api: components.Api$.outboundSchema.optional(),
            error: errors.ErrorT$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                api: "Api",
                error: "Error",
            });
        });
}
