/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as errors from "../errors/index.js";

export type ValidateApiKeyResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  apiKeyDetails?: components.ApiKeyDetails | undefined;
  /**
   * Default error response
   */
  error?: errors.ErrorT | undefined;
};

/** @internal */
export const ValidateApiKeyResponse$inboundSchema: z.ZodType<
  ValidateApiKeyResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  ApiKeyDetails: components.ApiKeyDetails$inboundSchema.optional(),
  Error: errors.ErrorT$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "ApiKeyDetails": "apiKeyDetails",
    "Error": "error",
  });
});

/** @internal */
export type ValidateApiKeyResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  ApiKeyDetails?: components.ApiKeyDetails$Outbound | undefined;
  Error?: errors.ErrorT$Outbound | undefined;
};

/** @internal */
export const ValidateApiKeyResponse$outboundSchema: z.ZodType<
  ValidateApiKeyResponse$Outbound,
  z.ZodTypeDef,
  ValidateApiKeyResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  apiKeyDetails: components.ApiKeyDetails$outboundSchema.optional(),
  error: errors.ErrorT$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    apiKeyDetails: "ApiKeyDetails",
    error: "Error",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ValidateApiKeyResponse$ {
  /** @deprecated use `ValidateApiKeyResponse$inboundSchema` instead. */
  export const inboundSchema = ValidateApiKeyResponse$inboundSchema;
  /** @deprecated use `ValidateApiKeyResponse$outboundSchema` instead. */
  export const outboundSchema = ValidateApiKeyResponse$outboundSchema;
  /** @deprecated use `ValidateApiKeyResponse$Outbound` instead. */
  export type Outbound = ValidateApiKeyResponse$Outbound;
}
