/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export enum Level {
  Allowed = "allowed",
  Warning = "warning",
  Blocked = "blocked",
}

export type AccessDetails = {
  generationAllowed: boolean;
  message: string;
  level?: Level | undefined;
};

/** @internal */
export const Level$inboundSchema: z.ZodNativeEnum<typeof Level> = z.nativeEnum(
  Level,
);

/** @internal */
export const AccessDetails$inboundSchema: z.ZodType<
  AccessDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  generation_allowed: z.boolean(),
  message: z.string(),
  level: Level$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "generation_allowed": "generationAllowed",
  });
});

export function accessDetailsFromJSON(
  jsonString: string,
): SafeParseResult<AccessDetails, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccessDetails$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccessDetails' from JSON`,
  );
}
