/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * Request body of tags to add to a revision
 */
export type AddTags = {
  /**
   * revision digest to add tags too sha256:...
   */
  revisionDigest: string;
  /**
   * string tags to add to the revision
   */
  tags: Array<string>;
};

/** @internal */
export type AddTags$Outbound = {
  revision_digest: string;
  tags: Array<string>;
};

/** @internal */
export const AddTags$outboundSchema: z.ZodType<
  AddTags$Outbound,
  z.ZodTypeDef,
  AddTags
> = z.object({
  revisionDigest: z.string(),
  tags: z.array(z.string()),
}).transform((v) => {
  return remap$(v, {
    revisionDigest: "revision_digest",
  });
});

export function addTagsToJSON(addTags: AddTags): string {
  return JSON.stringify(AddTags$outboundSchema.parse(addTags));
}
