/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * A filter is a key-value pair that can be used to filter a list of requests.
 */
export type Filter = {
    /**
     * The key of the filter.
     */
    key: string;
    /**
     * The operator of the filter.
     */
    operator: string;
    /**
     * The value of the filter.
     */
    value: string;
};

/** @internal */
export namespace Filter$ {
    export const inboundSchema: z.ZodType<Filter, z.ZodTypeDef, unknown> = z.object({
        key: z.string(),
        operator: z.string(),
        value: z.string(),
    });

    export type Outbound = {
        key: string;
        operator: string;
        value: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Filter> = z.object({
        key: z.string(),
        operator: z.string(),
        value: z.string(),
    });
}
