/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Tag, Tag$ } from "./tag.js";
import * as z from "zod";

export type GetTagsResponse = {
    items: Array<Tag>;
};

/** @internal */
export namespace GetTagsResponse$ {
    export const inboundSchema: z.ZodType<GetTagsResponse, z.ZodTypeDef, unknown> = z.object({
        items: z.array(Tag$.inboundSchema),
    });

    export type Outbound = {
        items: Array<Tag$.Outbound>;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetTagsResponse> = z.object({
        items: z.array(Tag$.outboundSchema),
    });
}
