/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Tag, Tag$inboundSchema } from "./tag.js";

export type GetTagsResponse = {
  items: Array<Tag>;
};

/** @internal */
export const GetTagsResponse$inboundSchema: z.ZodType<
  GetTagsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(Tag$inboundSchema),
});

export function getTagsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetTagsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTagsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTagsResponse' from JSON`,
  );
}
