/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * A request to store publishing secrets for a github target
 */
export type GithubStorePublishingSecretsRequest = {
  /**
   * The generation lock ID
   */
  generateGenLockId: string;
  /**
   * A map of secrets to store in the GitHub target
   */
  secrets?: { [k: string]: string } | undefined;
};

/** @internal */
export type GithubStorePublishingSecretsRequest$Outbound = {
  generate_gen_lock_id: string;
  secrets?: { [k: string]: string } | undefined;
};

/** @internal */
export const GithubStorePublishingSecretsRequest$outboundSchema: z.ZodType<
  GithubStorePublishingSecretsRequest$Outbound,
  z.ZodTypeDef,
  GithubStorePublishingSecretsRequest
> = z.object({
  generateGenLockId: z.string(),
  secrets: z.record(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    generateGenLockId: "generate_gen_lock_id",
  });
});

export function githubStorePublishingSecretsRequestToJSON(
  githubStorePublishingSecretsRequest: GithubStorePublishingSecretsRequest,
): string {
  return JSON.stringify(
    GithubStorePublishingSecretsRequest$outboundSchema.parse(
      githubStorePublishingSecretsRequest,
    ),
  );
}
