/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * A valid response containing MISSING publishing secret keys for a github target
 */
export type GithubMissingPublishingSecretsResponse = {
  missingSecrets?: Array<string> | undefined;
};

/** @internal */
export const GithubMissingPublishingSecretsResponse$inboundSchema: z.ZodType<
  GithubMissingPublishingSecretsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  missing_secrets: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "missing_secrets": "missingSecrets",
  });
});

export function githubMissingPublishingSecretsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GithubMissingPublishingSecretsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GithubMissingPublishingSecretsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GithubMissingPublishingSecretsResponse' from JSON`,
  );
}
