/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

/**
 * A request to store publishing secrets for a github target
 */
export type GithubStorePublishingSecretsRequest = {
    /**
     * The generation lock ID
     */
    generateGenLockId: string;
    /**
     * A map of secrets to store in the GitHub target
     */
    secrets?: { [k: string]: string } | undefined;
};

/** @internal */
export namespace GithubStorePublishingSecretsRequest$ {
    export const inboundSchema: z.ZodType<
        GithubStorePublishingSecretsRequest,
        z.ZodTypeDef,
        unknown
    > = z
        .object({
            generate_gen_lock_id: z.string(),
            secrets: z.record(z.string()).optional(),
        })
        .transform((v) => {
            return remap$(v, {
                generate_gen_lock_id: "generateGenLockId",
            });
        });

    export type Outbound = {
        generate_gen_lock_id: string;
        secrets?: { [k: string]: string } | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GithubStorePublishingSecretsRequest
    > = z
        .object({
            generateGenLockId: z.string(),
            secrets: z.record(z.string()).optional(),
        })
        .transform((v) => {
            return remap$(v, {
                generateGenLockId: "generate_gen_lock_id",
            });
        });
}
