/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * A request to configure GitHub code samples
 */
export type GithubConfigureCodeSamplesRequest = {
    /**
     * The GitHub organization name
     */
    org: string;
    /**
     * The GitHub repository name
     */
    repo: string;
    /**
     * The target name for the code samples
     */
    targetName: string;
};

/** @internal */
export namespace GithubConfigureCodeSamplesRequest$ {
    export const inboundSchema: z.ZodType<
        GithubConfigureCodeSamplesRequest,
        z.ZodTypeDef,
        unknown
    > = z.object({
        org: z.string(),
        repo: z.string(),
        targetName: z.string(),
    });

    export type Outbound = {
        org: string;
        repo: string;
        targetName: string;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GithubConfigureCodeSamplesRequest
    > = z.object({
        org: z.string(),
        repo: z.string(),
        targetName: z.string(),
    });
}
