/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

/**
 * response to a getting the latest action run on a GitHub request
 */
export type GithubGetActionResponse = {
    /**
     * The URL for latest action run if available
     */
    runUrl?: string | undefined;
    /**
     * The status of the latest action run if available
     */
    runStatus?: string | undefined;
};

/** @internal */
export namespace GithubGetActionResponse$ {
    export const inboundSchema: z.ZodType<GithubGetActionResponse, z.ZodTypeDef, unknown> = z
        .object({
            run_url: z.string().optional(),
            run_status: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                run_url: "runUrl",
                run_status: "runStatus",
            });
        });

    export type Outbound = {
        run_url?: string | undefined;
        run_status?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GithubGetActionResponse> = z
        .object({
            runUrl: z.string().optional(),
            runStatus: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                runUrl: "run_url",
                runStatus: "run_status",
            });
        });
}
