/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

/**
 * A request to configure a GitHub target
 */
export type GithubConfigureTargetRequest = {
    /**
     * The GitHub organization name
     */
    org: string;
    /**
     * The GitHub repository name
     */
    repoName: string;
};

/** @internal */
export namespace GithubConfigureTargetRequest$ {
    export const inboundSchema: z.ZodType<GithubConfigureTargetRequest, z.ZodTypeDef, unknown> = z
        .object({
            org: z.string(),
            repo_name: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                repo_name: "repoName",
            });
        });

    export type Outbound = {
        org: string;
        repo_name: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GithubConfigureTargetRequest> = z
        .object({
            org: z.string(),
            repoName: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                repoName: "repo_name",
            });
        });
}
