/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { OASInfo, OASInfo$ } from "./oasinfo.js";
import { OASOperation, OASOperation$ } from "./oasoperation.js";
import * as z from "zod";

export type OASSummary = {
    info: OASInfo;
    operations: Array<OASOperation>;
};

/** @internal */
export namespace OASSummary$ {
    export const inboundSchema: z.ZodType<OASSummary, z.ZodTypeDef, unknown> = z.object({
        info: OASInfo$.inboundSchema,
        operations: z.array(OASOperation$.inboundSchema),
    });

    export type Outbound = {
        info: OASInfo$.Outbound;
        operations: Array<OASOperation$.Outbound>;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, OASSummary> = z.object({
        info: OASInfo$.outboundSchema,
        operations: z.array(OASOperation$.outboundSchema),
    });
}
