/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  OrganizationUsage,
  OrganizationUsage$inboundSchema,
} from "./organizationusage.js";

/**
 * A billing summary of organization usage
 */
export type OrganizationUsageResponse = {
  usage: Array<OrganizationUsage>;
  /**
   * Expiry date of the free trial, will be null if no trial
   */
  freeTrialExpiry?: Date | undefined;
  /**
   * Total number of allowed languages, -1 if unlimited
   */
  totalAllowedLanguages: number;
  /**
   * List of allowed languages
   */
  allowedLanguages: Array<string>;
};

/** @internal */
export const OrganizationUsageResponse$inboundSchema: z.ZodType<
  OrganizationUsageResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  usage: z.array(OrganizationUsage$inboundSchema),
  free_trial_expiry: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
  total_allowed_languages: z.number().int(),
  allowed_languages: z.array(z.string()),
}).transform((v) => {
  return remap$(v, {
    "free_trial_expiry": "freeTrialExpiry",
    "total_allowed_languages": "totalAllowedLanguages",
    "allowed_languages": "allowedLanguages",
  });
});

export function organizationUsageResponseFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationUsageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationUsageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationUsageResponse' from JSON`,
  );
}
