/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export enum OrganizationAccountType {
    Free = "free",
    ScaleUp = "scale-up",
    Enterprise = "enterprise",
}

/**
 * A speakeasy organization
 */
export type Organization = {
    id: string;
    name: string;
    slug?: string | undefined;
    accountType: OrganizationAccountType;
    telemetryDisabled: boolean;
    createdAt?: Date | undefined;
    updatedAt?: Date | undefined;
};

/** @internal */
export namespace OrganizationAccountType$ {
    export const inboundSchema: z.ZodNativeEnum<typeof OrganizationAccountType> =
        z.nativeEnum(OrganizationAccountType);
    export const outboundSchema: z.ZodNativeEnum<typeof OrganizationAccountType> = inboundSchema;
}

/** @internal */
export namespace Organization$ {
    export const inboundSchema: z.ZodType<Organization, z.ZodTypeDef, unknown> = z
        .object({
            id: z.string(),
            name: z.string(),
            slug: z.string().optional(),
            account_type: OrganizationAccountType$.inboundSchema,
            telemetry_disabled: z.boolean(),
            created_at: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
                .optional(),
            updated_at: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
                .optional(),
        })
        .transform((v) => {
            return remap$(v, {
                account_type: "accountType",
                telemetry_disabled: "telemetryDisabled",
                created_at: "createdAt",
                updated_at: "updatedAt",
            });
        });

    export type Outbound = {
        id: string;
        name: string;
        slug?: string | undefined;
        account_type: string;
        telemetry_disabled: boolean;
        created_at?: string | undefined;
        updated_at?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Organization> = z
        .object({
            id: z.string(),
            name: z.string(),
            slug: z.string().optional(),
            accountType: OrganizationAccountType$.outboundSchema,
            telemetryDisabled: z.boolean(),
            createdAt: z
                .date()
                .transform((v) => v.toISOString())
                .optional(),
            updatedAt: z
                .date()
                .transform((v) => v.toISOString())
                .optional(),
        })
        .transform((v) => {
            return remap$(v, {
                accountType: "account_type",
                telemetryDisabled: "telemetry_disabled",
                createdAt: "created_at",
                updatedAt: "updated_at",
            });
        });
}
