/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type OrganizationUsage = {
  /**
   * Number of operations performed
   */
  numberOfOperations: number;
  /**
   * Maximum Number of operations per SDK specific in contract
   */
  maxOperations: number;
  /**
   * The programming language used
   */
  language: string;
  /**
   * Features that have been used
   */
  usedFeatures: Array<string>;
  /**
   * Features that are accessible
   */
  accessibleFeatures: Array<string>;
  /**
   * Indicates if the features are accessible
   */
  accessible: boolean;
  /**
   * List of workspace IDs
   */
  workspaces: Array<string>;
  /**
   * List of generation lock IDs
   */
  genLockIds: Array<string>;
};

/** @internal */
export const OrganizationUsage$inboundSchema: z.ZodType<
  OrganizationUsage,
  z.ZodTypeDef,
  unknown
> = z.object({
  number_of_operations: z.number().int(),
  max_operations: z.number().int(),
  language: z.string(),
  used_features: z.array(z.string()),
  accessible_features: z.array(z.string()),
  accessible: z.boolean(),
  workspaces: z.array(z.string()),
  gen_lock_ids: z.array(z.string()),
}).transform((v) => {
  return remap$(v, {
    "number_of_operations": "numberOfOperations",
    "max_operations": "maxOperations",
    "used_features": "usedFeatures",
    "accessible_features": "accessibleFeatures",
    "gen_lock_ids": "genLockIds",
  });
});

export function organizationUsageFromJSON(
  jsonString: string,
): SafeParseResult<OrganizationUsage, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OrganizationUsage$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OrganizationUsage' from JSON`,
  );
}
