/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type PreflightRequest = {
    namespaceName: string;
};

/** @internal */
export namespace PreflightRequest$ {
    export const inboundSchema: z.ZodType<PreflightRequest, z.ZodTypeDef, unknown> = z
        .object({
            namespace_name: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                namespace_name: "namespaceName",
            });
        });

    export type Outbound = {
        namespace_name: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PreflightRequest> = z
        .object({
            namespaceName: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                namespaceName: "namespace_name",
            });
        });
}
