/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export enum TargetResource {
  Document = "document",
}

/**
 * A token used to publish to a target
 */
export type PublishingToken = {
  id: string;
  token: string;
  validUntil: Date;
  tokenName: string;
  targetId: string;
  targetResource: TargetResource;
  createdAt: Date;
  updatedAt?: Date | undefined;
  createdBy: string;
  updatedBy?: string | undefined;
  organizationId: string;
  workspaceId: string;
};

/** @internal */
export const TargetResource$inboundSchema: z.ZodNativeEnum<
  typeof TargetResource
> = z.nativeEnum(TargetResource);

/** @internal */
export const PublishingToken$inboundSchema: z.ZodType<
  PublishingToken,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  token: z.string(),
  valid_until: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ),
  token_name: z.string(),
  target_id: z.string(),
  target_resource: TargetResource$inboundSchema,
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  created_by: z.string(),
  updated_by: z.string().optional(),
  organization_id: z.string(),
  workspace_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "valid_until": "validUntil",
    "token_name": "tokenName",
    "target_id": "targetId",
    "target_resource": "targetResource",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "created_by": "createdBy",
    "updated_by": "updatedBy",
    "organization_id": "organizationId",
    "workspace_id": "workspaceId",
  });
});

export function publishingTokenFromJSON(
  jsonString: string,
): SafeParseResult<PublishingToken, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PublishingToken$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PublishingToken' from JSON`,
  );
}
