/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export enum Type {
  Linting = "linting",
  Changes = "changes",
}

export type Report = {
  type?: Type | undefined;
};

/** @internal */
export const Type$outboundSchema: z.ZodNativeEnum<typeof Type> = z.nativeEnum(
  Type,
);

/** @internal */
export type Report$Outbound = {
  type?: string | undefined;
};

/** @internal */
export const Report$outboundSchema: z.ZodType<
  Report$Outbound,
  z.ZodTypeDef,
  Report
> = z.object({
  type: Type$outboundSchema.optional(),
});

export function reportToJSON(report: Report): string {
  return JSON.stringify(Report$outboundSchema.parse(report));
}
