/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export enum Type {
    Linting = "linting",
    Changes = "changes",
}

export type Report = {
    type?: Type | undefined;
};

/** @internal */
export namespace Type$ {
    export const inboundSchema: z.ZodNativeEnum<typeof Type> = z.nativeEnum(Type);
    export const outboundSchema: z.ZodNativeEnum<typeof Type> = inboundSchema;
}

/** @internal */
export namespace Report$ {
    export const inboundSchema: z.ZodType<Report, z.ZodTypeDef, unknown> = z.object({
        type: Type$.inboundSchema.optional(),
    });

    export type Outbound = {
        type?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Report> = z.object({
        type: Type$.outboundSchema.optional(),
    });
}
