/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  RevisionContentsMetadata,
  RevisionContentsMetadata$inboundSchema,
} from "./revisioncontentsmetadata.js";

export type Revision = {
  /**
   * Format {namespace_id}/{revision_digest}
   */
  id: string;
  digest: string;
  namespaceName: string;
  tags: Array<string>;
  contentsMetadata?: RevisionContentsMetadata | undefined;
  createdAt: Date;
  updatedAt: Date;
};

/** @internal */
export const Revision$inboundSchema: z.ZodType<
  Revision,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  digest: z.string(),
  namespace_name: z.string(),
  tags: z.array(z.string()),
  contents_metadata: RevisionContentsMetadata$inboundSchema.optional(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
}).transform((v) => {
  return remap$(v, {
    "namespace_name": "namespaceName",
    "contents_metadata": "contentsMetadata",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

export function revisionFromJSON(
  jsonString: string,
): SafeParseResult<Revision, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Revision$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Revision' from JSON`,
  );
}
