/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

/**
 * A Schema represents an API schema for a particular Api and Version.
 */
export type Schema = {
    /**
     * The ID of the Api this Schema belongs to.
     */
    apiId: string;
    /**
     * Creation timestamp.
     */
    createdAt: Date;
    /**
     * A detailed description of the Schema.
     */
    description: string;
    /**
     * An ID referencing this particular revision of the Schema.
     */
    revisionId: string;
    /**
     * The version ID of the Api this Schema belongs to.
     */
    versionId: string;
    /**
     * The workspace ID this Schema belongs to.
     */
    workspaceId: string;
};

/** @internal */
export namespace Schema$ {
    export const inboundSchema: z.ZodType<Schema, z.ZodTypeDef, unknown> = z
        .object({
            api_id: z.string(),
            created_at: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v)),
            description: z.string(),
            revision_id: z.string(),
            version_id: z.string(),
            workspace_id: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                api_id: "apiId",
                created_at: "createdAt",
                revision_id: "revisionId",
                version_id: "versionId",
                workspace_id: "workspaceId",
            });
        });

    export type Outbound = {
        api_id: string;
        created_at: string;
        description: string;
        revision_id: string;
        version_id: string;
        workspace_id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Schema> = z
        .object({
            apiId: z.string(),
            createdAt: z.date().transform((v) => v.toISOString()),
            description: z.string(),
            revisionId: z.string(),
            versionId: z.string(),
            workspaceId: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                apiId: "api_id",
                createdAt: "created_at",
                revisionId: "revision_id",
                versionId: "version_id",
                workspaceId: "workspace_id",
            });
        });
}
