/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export enum Format {
  Json = "json",
  Yaml = "yaml",
}

export type SchemaStoreItem = {
  id: string;
  spec: string;
  packageName: string;
  sdkClassname: string;
  createdAt: Date;
  format: Format;
};

/** @internal */
export const Format$inboundSchema: z.ZodNativeEnum<typeof Format> = z
  .nativeEnum(Format);

/** @internal */
export const SchemaStoreItem$inboundSchema: z.ZodType<
  SchemaStoreItem,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  spec: z.string(),
  packageName: z.string(),
  sdkClassname: z.string(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  format: Format$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
  });
});

export function schemaStoreItemFromJSON(
  jsonString: string,
): SafeParseResult<SchemaStoreItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SchemaStoreItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SchemaStoreItem' from JSON`,
  );
}
