/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type Security = {
  apiKey?: string | undefined;
  workspaceIdentifier?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export type Security$Outbound = {
  APIKey?: string | undefined;
  WorkspaceIdentifier?: string | undefined;
  Bearer?: string | undefined;
};

/** @internal */
export const Security$outboundSchema: z.ZodType<
  Security$Outbound,
  z.ZodTypeDef,
  Security
> = z.object({
  apiKey: z.string().optional(),
  workspaceIdentifier: z.string().optional(),
  bearer: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    apiKey: "APIKey",
    workspaceIdentifier: "WorkspaceIdentifier",
    bearer: "Bearer",
  });
});

export function securityToJSON(security: Security): string {
  return JSON.stringify(Security$outboundSchema.parse(security));
}
