/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Annotations, Annotations$inboundSchema } from "./annotations.js";

/**
 * V2 descriptor
 */
export type V2Descriptor = {
  /**
   * Digest
   */
  digest?: string | undefined;
  /**
   * Media type
   */
  mediaType?: string | undefined;
  /**
   * Size
   */
  size?: number | undefined;
  /**
   * Annotations
   */
  annotations?: Annotations | undefined;
};

/** @internal */
export const V2Descriptor$inboundSchema: z.ZodType<
  V2Descriptor,
  z.ZodTypeDef,
  unknown
> = z.object({
  digest: z.string().optional(),
  mediaType: z.string().optional(),
  size: z.number().int().optional(),
  annotations: Annotations$inboundSchema.optional(),
});

export function v2DescriptorFromJSON(
  jsonString: string,
): SafeParseResult<V2Descriptor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2Descriptor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2Descriptor' from JSON`,
  );
}
