/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

/**
 * A set of keys and associated values, attached to a particular version of an Api.
 */
export type VersionMetadata = {
    /**
     * The ID of the Api this Metadata belongs to.
     */
    apiId: string;
    /**
     * Creation timestamp.
     */
    createdAt: Date;
    /**
     * The key for this metadata.
     */
    metaKey: string;
    /**
     * One of the values for this metadata.
     */
    metaValue: string;
    /**
     * The version ID of the Api this Metadata belongs to.
     */
    versionId: string;
    /**
     * The workspace ID this Metadata belongs to.
     */
    workspaceId: string;
};

/** @internal */
export namespace VersionMetadata$ {
    export const inboundSchema: z.ZodType<VersionMetadata, z.ZodTypeDef, unknown> = z
        .object({
            api_id: z.string(),
            created_at: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v)),
            meta_key: z.string(),
            meta_value: z.string(),
            version_id: z.string(),
            workspace_id: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                api_id: "apiId",
                created_at: "createdAt",
                meta_key: "metaKey",
                meta_value: "metaValue",
                version_id: "versionId",
                workspace_id: "workspaceId",
            });
        });

    export type Outbound = {
        api_id: string;
        created_at: string;
        meta_key: string;
        meta_value: string;
        version_id: string;
        workspace_id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, VersionMetadata> = z
        .object({
            apiId: z.string(),
            createdAt: z.date().transform((v) => v.toISOString()),
            metaKey: z.string(),
            metaValue: z.string(),
            versionId: z.string(),
            workspaceId: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                apiId: "api_id",
                createdAt: "created_at",
                metaKey: "meta_key",
                metaValue: "meta_value",
                versionId: "version_id",
                workspaceId: "workspace_id",
            });
        });
}
