/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * enum value workspace feature flag
 */
export enum WorkspaceFeatureFlag {
  SchemaRegistry = "schema_registry",
  ChangesReport = "changes_report",
  SkipSchemaRegistry = "skip_schema_registry",
  Webhooks = "webhooks",
}
/**
 * enum value workspace feature flag
 */
export type WorkspaceFeatureFlagOpen = OpenEnum<typeof WorkspaceFeatureFlag>;

/** @internal */
export const WorkspaceFeatureFlag$inboundSchema: z.ZodType<
  WorkspaceFeatureFlagOpen,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(WorkspaceFeatureFlag);
/** @internal */
export const WorkspaceFeatureFlag$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  WorkspaceFeatureFlagOpen
> = openEnums.outboundSchema(WorkspaceFeatureFlag);
