/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { SSOMetadata, SSOMetadata$inboundSchema } from "./ssometadata.js";
import { User, User$inboundSchema } from "./user.js";

/**
 * Workspace team response
 */
export type WorkspaceTeamResponse = {
  users: Array<User>;
  /**
   * SSO metadata for a workspace
   */
  ssoMetadata?: SSOMetadata | undefined;
};

/** @internal */
export const WorkspaceTeamResponse$inboundSchema: z.ZodType<
  WorkspaceTeamResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  users: z.array(User$inboundSchema),
  sso_metadata: SSOMetadata$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "sso_metadata": "ssoMetadata",
  });
});

export function workspaceTeamResponseFromJSON(
  jsonString: string,
): SafeParseResult<WorkspaceTeamResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorkspaceTeamResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorkspaceTeamResponse' from JSON`,
  );
}
